### PR TITLE
Avoid gzrtp compile warnings

### PR DESCRIPTION
**Pull request by juha-h**

### CODE REVIEW

**Comment by juha-h** [comment]
There is still alot more when cmake build is used.

**Comment by juha-h** [comment]
I added more -Wno-Xs and now there is only two unused param warnings left.  But is it really OK to suppress the warnings?

**Comment by juha-h** [comment]
Finally, why are these generated?
```
cd /usr/src/orig/baresip/build/modules/gzrtp && /usr/bin/c++ -DARCH=\"x86_64\" -DHAVE_ATOMIC -DHAVE_EPOLL -DHAVE_EXECINFO -DHAVE_FORK -DHAVE_GETIFADDRS -DHAVE_GETOPT -DHAVE_INET6 -DHAVE_POLL -DHAVE_PTHREAD -DHAVE_PWD_H -DHAVE_ROUTE_LIST -DHAVE_SELECT -DHAVE_SELECT_H -DHAVE_SETRLIMIT -DHAVE_SIGNAL -DHAVE_STRERROR_R -DHAVE_STRINGS_H -DHAVE_SYSLOG -DHAVE_SYS_TIME_H -DHAVE_UNAME -DHAVE_UNISTD_H -DLINUX -DOS=\"Linux\" -DSHARE_PATH=\"\" -DUSE_DTLS -DUSE_OPENSSL -DUSE_OPENSSL_AES -DUSE_OPENSSL_DTLS -DUSE_OPENSSL_HMAC -DUSE_OPENSSL_SRTP -DUSE_TLS -DUSE_ZLIB -DVERSION=\"2.7.0\" -DVER_MAJOR=2 -DVER_MINOR=7 -DVER_PATCH=0 -Dgzrtp_EXPORTS -I/usr/src/orig/baresip/include -I/usr/src/orig/baresip/src -I/usr/src/orig/re/include -I/usr/src/orig/rem/include -I/usr/src/orig/ZRTPCPP -I/usr/src/orig/ZRTPCPP/zrtp -I/usr/src/orig/ZRTPCPP/srtp -fPIC -pedantic -Wall -Wbad-function-cast -Wcast-align -Wextra -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-strict-aliasing -Wold-style-definition -Wshadow -Waggregate-return -Wstrict-prototypes -Wuninitialized -Wvla -Wno-unknown-pragmas -Wno-shadow -Wno-ignored-qualifiers -Wno-aggregate-return -Wno-pedantic -Wno-missing-field-initializers -MD -MT modules/gzrtp/CMakeFiles/gzrtp.dir/gzrtp.cpp.o -MF CMakeFiles/gzrtp.dir/gzrtp.cpp.o.d -o CMakeFiles/gzrtp.dir/gzrtp.cpp.o -c /usr/src/orig/baresip/modules/gzrtp/gzrtp.cpp
cc1plus: warning: command-line option ‘-Wbad-function-cast’ is valid for C/ObjC but not for C++
cc1plus: warning: command-line option ‘-Wmissing-prototypes’ is valid for C/ObjC but not for C++
cc1plus: warning: command-line option ‘-Wnested-externs’ is valid for C/ObjC but not for C++
cc1plus: warning: command-line option ‘-Wold-style-definition’ is valid for C/ObjC but not for C++
cc1plus: warning: command-line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
```
Shouldn't cmake figure out what -Ws to add for the used compiler?

**Comment by alfredh** [comment]
I think it is better to fix the warnings instead of suppressing them.

There are some warning options that are available for C, some for C++ and some for both C/C++.

**Comment by juha-h** [comment]
I found that the command-line option warnings in above come from main CMakeLists.txt:
```
if(MSVC)
  add_compile_options("/W3")
else()
  add_compile_options(
    -pedantic
    -Wall
    -Wbad-function-cast
    -Wcast-align
    -Wextra
    -Wmissing-declarations
    -Wmissing-prototypes
    -Wnested-externs
    -Wno-strict-aliasing
    -Wold-style-definition
    -Wshadow -Waggregate-return
    -Wstrict-prototypes
    -Wuninitialized
    -Wvla
  )
endif()
```
Should there be some condition on the compiler/language?

**Comment by sreimers** [comment]
Something like this is the preferred method to separate I think:

```cmake
set(c_flags -Wall -Wextra)
add_compile_options(
  "$<$<COMPILE_LANGUAGE:C>:${c_flags}>"
  "$<$<COMPILE_LANGUAGE:CXX>:${cxx_flags}>"
)
```

**Comment by juha-h** [comment]
> I think it is better to fix the warnings instead of suppressing them.

Really fixing this?
```
In file included from /usr/src/orig/re/include/re.h:16,
                 from /usr/src/orig/baresip/modules/gzrtp/messages.cpp:8:
/usr/src/orig/re/include/re_fmt.h:96:35: warning: ‘int re_printf(const char*, ...)’ hides constructor for ‘struct re_printf’ [-Wshadow]
   96 | int re_printf(const char *fmt, ...);
      |                                   ^
In file included from /usr/src/orig/re/include/re.h:24,
                 from /usr/src/orig/baresip/modules/gzrtp/messages.cpp:8:
/usr/src/orig/re/include/re_async.h:16:16: warning: ‘int re_async(re_async*, int (*)(void*), void (*)(int, void*), void*)’ hides constructor for ‘struct re_async’ [-Wshadow]
   16 |       void *arg);
      |                ^
```

**Comment by juha-h** [comment]
> Something like this is the preferred method to separate I think:
> 
> ```cmake
> set(c_flags -Wall -Wextra)
> add_compile_options(
>   "$<$<COMPILE_LANGUAGE:C>:${c_flags}>"
>   "$<$<COMPILE_LANGUAGE:CXX>:${cxx_flags}>"
> )
> ```
Looks good.  I'll try again when this is done.

**Comment by juha-h** [comment]
> Something like this is the preferred method to separate I think:
> 
> ```cmake
> set(c_flags -Wall -Wextra)
> add_compile_options(
>   "$<$<COMPILE_LANGUAGE:C>:${c_flags}>"
>   "$<$<COMPILE_LANGUAGE:CXX>:${cxx_flags}>"
> )
> ```

It turned out that `is valid for C/ObjC but not for C++` warnings only appear if c++ compiler is GNU g++.  They do not appear if c++ compiler is clang++.  So the right options not only depend on language, but also on compiler.

**Pull request merged**
