### PR TITLE
call: magic check in sipsess_desc_handler()

### PR DESCRIPTION
**Pull request by cspiel1**

### CODE REVIEW

**Comment by cspiel1** [comment]
@juha-h Please try to reproduce the crash! Maybe you get the MAGIC_CHECK warning.
Which steps lead to this crash?

**Comment by juha-h** [comment]
I have now applied this PR in my two test devices, but don't know how to reproduce the crash

Is it so that magic check just prints a log message, but execution of the code continues and the crash will happen like before?

If there are no negative consequences of the check, it would be good idea to merge the PR.

**Comment by sreimers** [comment]
With RELEASE=1 https://github.com/juha-h/libbaresip-android/blob/master/Makefile#L114 MAGIC_CHECK is disabled. without it prints a warning and calls BREAKPOINT which is helpfull in debugger.

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> With RELEASE=1
> https://github.com/juha-h/libbaresip-android/blob/master/Makefile#L114
> MAGIC_CHECK is disabled. without it prints a warning and calls
> BREAKPOINT which is helpfull in debugger.

OK, I set RELEASE=0 in the build that I use in my own device.  I'll wait
if/when the crash happens again.

-- Juha

**Comment by sreimers** [comment]
You have to set `RELEASE=`

**Comment by juha-h** [comment]
OK, now I have RELEASE=

**Comment by juha-h** [comment]
I got the same crash again:
```
          sipsess_desc_handler
                                                                                                                                     /usr/src/libbaresip-android/baresip/src/call.c:2102:18
#01 0x00000000001deea0 /data/app/~~cF2KMkQKhKyJglo6ONuENA==/com.tutpro.baresip.plus-9KkP7Aq4CjeMvY3tC45osA==/base.apk!libbaresip.so (offset 0x2a7000) (BuildId: 784a70d39d02cab3a613c9f6856df84441b819ca)
```

Line 2102 is same as as before:
```
	if (!call->acc->mnat)
```
MAGIC_CHECK gave:
```
11-22 17:49:10.685 17601 17698 D Baresip+ Lib: sipsess_desc_handler: wrong magic struct=0x786d998a98 (magic=0x00000000)
11-22 17:49:11.385 23080 23080 F DEBUG   :       #12 pc 000000000017acb8  /data/app/~~cF2KMkQKhKyJglo6ONuENA==/com.tutpro.baresip.plus-9KkP7Aq4CjeMvY3tC45osA==/base.apk!libbaresip.so (offset 0x2a7000) (Java_com_tutpro_baresip_plus_BaresipService_baresipStart+2932) (BuildId: 784a70d39d02cab3a613c9f6856df84441b819ca)
11-22 17:49:11.386 23080 23080 F DEBUG   :       #20 pc 0000000000019b44  [anon:dalvik-classes3.dex extracted in memory from /data/app/~~cF2KMkQKhKyJglo6ONuENA==/com.tutpro.baresip.plus-9KkP7Aq4CjeMvY3tC45osA==/base.apk!classes3.dex] (com.tutpro.baresip.plus.BaresipService.onStartCommand$lambda-2+52)
11-22 17:49:11.386 23080 23080 F DEBUG   :       #23 pc 0000000000018b58  [anon:dalvik-classes3.dex extracted in memory from /data/app/~~cF2KMkQKhKyJglo6ONuENA==/com.tutpro.baresip.plus-9KkP7Aq4CjeMvY3tC45osA==/base.apk!classes3.dex] (com.tutpro.baresip.plus.BaresipService.$r8$lambda$NKEUbIq1EO7RcC2chrxxrr9A-EQ)
11-22 17:49:11.386 23080 23080 F DEBUG   :       #26 pc 0000000000016ce0  [anon:dalvik-classes3.dex extracted in memory from /data/app/~~cF2KMkQKhKyJglo6ONuENA==/com.tutpro.baresip.plus-9KkP7Aq4CjeMvY3tC45osA==/base.apk!classes3.dex] (com.tutpro.baresip.plus.BaresipService$$ExternalSyntheticLambda2.run+8)
```

**Comment by juha-h** [comment]
From logs I see the events that lead to the crash:

- I made call from jh@test.tutpro.com to test@test.tutpro.com
- waited 6 seconds, didn't get ringing, and closed the call
- tried to re-register jh@test.tutpro.com, which didn't work either
- 3 seconds later decided to re-start baresip
- got the crash during unregistering/shutdown

The log is below.
```
11-22 17:49:00.162 17601 17601 D Baresip+ Lib: connecting ua 517514741400 to sip:test@test.tutpro.com with vmode 1, adir: 3, vdir: 0
11-22 17:49:00.162 17601 17698 D Baresip+ Lib: call: alloc with params laddr=10.174.60.68, af=AF_INET, use_rtp=1
11-22 17:49:00.163 17601 17698 D Baresip+ Lib:  [   zrtp main]: START SESSION INITIALIZATION. sID=14.
... more zrtp related lines
11-22 17:49:00.168 17601 17698 D Baresip+ Lib:  [   zrtp main]: ATTACH NEW STREAM - DONE.
11-22 17:49:00.168 17601 17698 D Baresip+ Lib: call: connecting to 'sip:test@test.tutpro.com'..
11-22 17:49:00.168 17601 17601 D Baresip+ Lib: sending ua/call 517514741400/518930800024 event call outgoing
11-22 17:49:00.168 17601 17601 D Baresip+: got uaEvent call outgoing/sip:jh@test.tutpro.com/518930800024
11-22 17:49:00.451 17601 17601 D Baresip+ Lib: ua event (CALL_LOCAL_SDP) offer
11-22 17:49:06.360 17601 17601 D Baresip+: AoR sip:jh@test.tutpro.com hanging up call 518930800024 with test
11-22 17:49:06.360 17601 17601 D Baresip+ Lib: hanging up call 517514741400/518930800024 with 0 
11-22 17:49:06.360 17601 17698 D Baresip+ Lib: call: terminate call 'a64eeaa78ef06b77' with sip:test@test.tutpro.com
11-22 17:49:06.362 17601 17698 D Baresip+ Lib: video: stopping video source ..
11-22 17:49:06.362 17601 17698 D Baresip+ Lib: video: stopping video display ..
11-22 17:49:06.362 17601 17601 D Baresip+ Lib: ua event (CALL_CLOSED) Connection reset by user
11-22 17:49:06.364 17601 17601 D Baresip+: AoR sip:jh@test.tutpro.com call 518930800024 is closed
11-22 17:49:06.627 17601 17698 D Baresip+ Lib: video: stopping video source ..
11-22 17:49:06.627 17601 17698 D Baresip+ Lib: video: stopping video display ..
11-22 17:49:06.628 17601 17698 D Baresip+ Lib: audio: destroyed (started=0)
11-22 17:49:06.628 17601 17698 D Baresip+ Lib:  [ zrtp engine]: STOP STREAM ID=28 mode=CLEAR state=ACTIVE.
11-22 17:49:06.628 17601 17698 D Baresip+ Lib:  [        zrtp]: 	Stream ID=0 UNKNOWN switching <NONE> ---> <NONE>.
11-22 17:49:06.628 17601 17698 D Baresip+ Lib:  [ zrtp engine]: STOP STREAM ID=29 mode=CLEAR state=ACTIVE.
11-22 17:49:06.628 17601 17698 D Baresip+ Lib:  [        zrtp]: 	Stream ID=0 UNKNOWN switching <NONE> ---> <NONE>.
11-22 17:49:06.630 17601 17698 D Baresip+ Lib:  [ zrtp engine]: STOP STREAM ID=0 mode=UNKNOWN state=NONE.
11-22 17:49:06.630 17601 17698 D Baresip+ Lib:  [ zrtp engine]: STOP STREAM ID=0 mode=UNKNOWN state=NONE.
11-22 17:49:07.627 17601 17698 D Baresip+ Lib: ua: ua_register sip:jh@test.tutpro.com
11-22 17:49:07.627 17601 17601 D Baresip+ Lib: ua event (REGISTERING) 
11-22 17:49:09.573 17601 17601 D Baresip+: quitRestart Restart = true
11-22 17:49:09.580 17601 17601 D Baresip+: Seconds remaining: 4
11-22 17:49:09.618 17601 17601 D Baresip+ Lib: ua_stop_all upon baresipStop
11-22 17:49:09.618 17601 17697 D Baresip+ Lib: calling ua_stop_all with force 0
11-22 17:49:09.618 17601 17697 D Baresip+ Lib: ua event (SHUTDOWN) 
11-22 17:49:09.618 17601 17698 D Baresip+ Lib: ua: stop all (forced=0)
11-22 17:49:09.620 17601 17697 D Baresip+ Lib: ua event (SHUTDOWN) 
11-22 17:49:09.620 17601 17697 D Baresip+ Lib: ua event (UNREGISTERING) 
11-22 17:49:09.621 17601 17697 D Baresip+ Lib: ua event (SHUTDOWN) 
11-22 17:49:09.622 17601 17697 D Baresip+ Lib: ua event (SHUTDOWN) 
11-22 17:49:09.632 17601 17698 D Baresip+ Lib: ua: in use (2) by app module
11-22 17:49:09.623 17601 17698 D Baresip+ Lib: mwi: shutdown of sip:bar@test.tutpro.com
11-22 17:49:10.121 17601 17697 D Baresip+ Lib: ua event (UNREGISTERING) 
11-22 17:49:10.132 17601 17697 D Baresip+ Lib: ua event (UNREGISTERING) 
11-22 17:49:10.581 17601 17601 D Baresip+: Seconds remaining: 3
11-22 17:49:10.685 17601 17698 D Baresip+ Lib: sipsess_desc_handler: wrong magic struct=0x786d998a98 (magic=0x00000000)
11-22 17:49:11.385 23080 23080 F DEBUG   :       #12 pc 000000000017acb8  /data/app/~~cF2KMkQKhKyJglo6ONuENA==/com.tutpro.baresip.plus-9KkP7Aq4CjeMvY3tC45osA==/base.apk!libbaresip.so (offset 0x2a7000) (Java_com_tutpro_baresip_plus_BaresipService_baresipStart+2932) (BuildId: 784a70d39d02cab3a613c9f6856df84441b819ca)
11-22 17:49:11.386 23080 23080 F DEBUG   :       #20 pc 0000000000019b44  [anon:dalvik-classes3.dex extracted in memory from /data/app/~~cF2KMkQKhKyJglo6ONuENA==/com.tutpro.baresip.plus-9KkP7Aq4CjeMvY3tC45osA==/base.apk!classes3.dex] (com.tutpro.baresip.plus.BaresipService.onStartCommand$lambda-2+52)
11-22 17:49:11.386 23080 23080 F DEBUG   :       #23 pc 0000000000018b58  [anon:dalvik-classes3.dex extracted in memory from /data/app/~~cF2KMkQKhKyJglo6ONuENA==/com.tutpro.baresip.plus-9KkP7Aq4CjeMvY3tC45osA==/base.apk!classes3.dex] (com.tutpro.baresip.plus.BaresipService.$r8$lambda$NKEUbIq1EO7RcC2chrxxrr9A-EQ)
11-22 17:49:11.386 23080 23080 F DEBUG   :       #26 pc 0000000000016ce0  [anon:dalvik-classes3.dex extracted in memory from /data/app/~~cF2KMkQKhKyJglo6ONuENA==/com.tutpro.baresip.plus-9KkP7Aq4CjeMvY3tC45osA==/base.apk!classes3.dex] (com.tutpro.baresip.plus.BaresipService$$ExternalSyntheticLambda2.run+8)
11-22 1
```

**Comment by juha-h** [comment]
So it is weird that 7 seconds after the calls is closed, sipsess_desc_handler() gets called.  No wonder that the call does not exist anymore.

**Comment by cspiel1** [comment]
I had an idea. This might be the solution:
https://github.com/baresip/re/pull/182

**Comment by juha-h** [comment]
I may have difficulties to reproduce the events that lead to the crash, but should be OK anyway to set `sess->desch = null` when session waits to be terminated.

**Comment by cspiel1** [comment]
Yes, I think that it has to be set NULL. The other function pointers are also set to NULL or the internal callback functions. This  was missing in the PR for commit ffd78c1415c53f5ea1fca6783bc840d399d8f78a

**Pull request merged**
