### PR TITLE
baresip.h: bump BARESIP_VERSION

### PR DESCRIPTION
**Pull request by cspiel1**
@sreimers I think that this should be done in the release steps. In the list it is in the "After Release" steps.

Should we merge it and set the tag with force to HEAD?

### CODE REVIEW

**Comment by sreimers** [comment]
> Should we merge it and set the tag with force to HEAD?

Yes please.

**Comment by cspiel1** [comment]
And should we squash the
```
commit e8686b8ad5028e3b4ea194c9209a19de0b3996be (HEAD -> after_release, origin/after_release)
Author: Christian Spielberger <c.spielberger@commend.com>
Date:   Sat Oct 1 10:55:22 2022 +0200

    baresip.h: bump BARESIP_VERSION
```
and push force to main??

**Comment by sreimers** [comment]
Oh no, no push force to public branches. Maybe v2.8.1 is better option.

**Comment by cspiel1** [comment]
Then v2.8.1 in Makefile, cmake and baresip.h?
Or also the CHANGELOG and "new release" on github?

**Comment by sreimers** [comment]
Yes needs a full release cycle.

**Comment by cspiel1** [comment]
So then a start with a fresh branch and PR.

**Pull request closed without merging**
