### PR TITLE
aubuf adaptive jitter buffer

### PR DESCRIPTION
**Pull request by cspiel1**
Relates to https://github.com/baresip/rem/pull/33
Discussion: https://github.com/baresip/re/discussions/184

- audio: adapt to adaptive aubuf, adaptive jbuf becomes obsolete
- audio: do not drop reordered packets
- config,stream: support for new jbuf type "minimize"
- stream: also for JBUF_ADAPTIVE decode immediately 

This makes JBUF_ADAPTIVE completely obsolete what is the final goal
of the current PR. This is necessary because otherwise no decoding
would be done if `jitter_buffer_type   adaptive` is configured.

An alternative would be to keep all the JBUF_ADAPTIVE functions in
stream.c and audio.c for a deprecation period.

@sreimers, @alfredh, @juha-h 
I suppose that nobody uses JBUF_ADAPTIVE except my company, thus I would prefer to directly drop all the obsolete code in baresip and also in `re/src/jbuf`. Let me know what you would prefer!
- A jbuf adaptive deprecation period, or
- immediate cleanup? This would/should not change the JBUF_FIXED behavior.

### CODE REVIEW

**Comment by sreimers** [comment]
Maybe we can cleanup and `jitter_buffer_type adaptive` is a deprecated fallback to JBUF_MINIMIZE?

**Comment by cspiel1** [comment]
> Maybe we can cleanup and `jitter_buffer_type adaptive` is a deprecated fallback to JBUF_MINIMIZE? Or we keep the `adaptive` term instead of `minimize`

I would prefer to drop all the jbuf adaptive code and keep the term `adaptive` instead of `minimize`. Should I do the cleanup right now?

**Comment by cspiel1** [comment]
Another question is:
Should we activate `AUBUF_ADAPTIVE` via baresip config to minimize the risk for the PR?
If everything works, `AUBUF_ADAPTIVE` should be used by default for optimal audio quality without having to adjust the buffers in the config on the network quality.

Currently, it is activated for `rx` and not for `tx`.

The `AUBUF_ADAPTIVE` in theory works also for `tx` in order to handle SW jitter of the audio source. But I still have to test this.

**Comment by sreimers** [comment]
> I would prefer to drop all the jbuf adaptive code and keep the term `adaptive` instead of `minimize`. Should I do the cleanup right now?

I would say yes, introducing a new term/config option is more confusing I think. And its easier to maintain/improve one adaptive jitter buffer solution.

> The `AUBUF_ADAPTIVE` in theory works also for `tx` in order to handle SW jitter of the audio source. But I still have to test this.

I think `rx` only is fine. the remote site has to deal with jitter anyway and for `tx` we have a thread mode for decoupling from the audio thread. Something we can consider for `rx` after merging this PR.

> Should we activate `AUBUF_ADAPTIVE` via baresip config to minimize the risk for the PR?
> If everything works, `AUBUF_ADAPTIVE` should be used by default for optimal audio quality without having to adjust the buffers in the config on the network quality.

Keeping `jitter_buffer_delay fixed` as default and migrate after some time sounds good.

**Comment by cspiel1** [comment]
Thus all combinations are possible and should work:
```
enum jbuf_type {
	JBUF_OFF,                   /* No jitter buffer --> best option for G.711 with AUBUF_ADAPTIVE */
	JBUF_FIXED,               /* The old behavior for packet re-ordering. */
	JBUF_ADAPTIVE         /* Packet re-ordering with minimum latency. --> Perfect for stateful codecs. */
};
```
```
enum aubuf_mode {
	AUBUF_FIXED,              /* The old behavior to simply decouple the threads. */
	AUBUF_ADAPTIVE        /* Compute jitter and optimize latency. */
};
```

`JBUF_FIXED + AUBUF_FIXED` will be default for some period.

In order to simplify the configuration for the user, finally these settings should be default:
- `AUBUF_ADAPTIVE`
- `JBUF_OFF` for state-less codecs and `JBUF_ADAPTIVE` for others. Maybe we find a solution to select this also autmatically.

**Comment by cspiel1** [comment]
Currently struggling around with the config for `enum aubuf_mode`, which is defined in `rem`.

If we add to `struct config_audio {`
```
enum aubuf_mode bufmod; /**< Audio buffer mode              */
```

Then `baresip.h` has it's first `rem.h` dependency. We need this setting in `audio.c` and in `modules/multicast/receiver.c` for now. And gcc tells me that "ISO C forbids forward references to ‘enum’ types".
 Should we
- read config setting `audio_buffer_mode` directly and compare the strings,
- instead of the `enum` use an `int` in `struct config_audio`,
- add the `#include <rem.h>` in all the c-files before `#include <baresip.h>`,
- split `baresip.h` into `baresip_config.h` and `baresip.h`

**Comment by cspiel1** [comment]
What is this? This has nothing to do with this PR.
```
src/udp/udp.c: In function ‘udp_flush’:
111
src/udp/udp.c:1004:27: error: pointer targets in passing argument 2 of ‘recvfrom’ differ in signedness [-Werror=pointer-sign]
112
 1004 |   while (recvfrom(us->fd, buf, sizeof(buf),
113
      |                           ^~~
114
      |                           |
115
      |                           uint8_t * {aka unsigned char *}
```

**Comment by alfredh** [comment]
this looks good.

please feel free to merge to main.

**Comment by cspiel1** [comment]
We have to complete first the re/rem PRs.

**Comment by cspiel1** [comment]
There is still missing the config for the aubuf mode. Should I implement one? Or is it okay that we switch to ABUF_ADAPTIVE for the rx stream?

Note: I had problems with the header file. https://github.com/baresip/baresip/pull/1784#issuecomment-1084420339

**Comment by sreimers** [comment]
A difficult decision, I am not sure, but would perhaps prefer this variant:
> * instead of the `enum` use an `int` in `struct config_audio`,

**Comment by cspiel1** [comment]
> A difficult decision, I am not sure, but would perhaps prefer this variant:
> 
> > * instead of the `enum` use an `int` in `struct config_audio`,

Thanks! For now a bool is enough.

**Comment by cspiel1** [comment]
I want to update a commit message "aubuf mode config draft". Then it's ready.

**Comment by cspiel1** [comment]
Now it should be okay for the merge. Thanks for reviewing!

**Comment by juha-h** [comment]
Currently I have in my Android app
```
jitter_buffer_type adaptive
jitter_buffer_delay 5-10
jitter_buffer_wish 6
```
After this commit, is that still valid or should it be changes somehow?  Is there a migration guide somewhere?

**Comment by juha-h** [comment]
juha-h writes:

> Currently I have in my Android app
> ```
> jitter_buffer_type adaptive
> jitter_buffer_delay 5-10
> jitter_buffer_wish 6
> ```
> After this commit, is that still valid or should it be changed
> somehow?  Is there a migration guide somewhere?

After checking core_config_template() function, the above still looks
valid.  Is there some relationship between jitter_buffer_type and the
new audio_buffer_mode?  Is it fine if audio_buffer_mode is "fixed" while 
jitter_buffer_type is "adaptive"?

**Comment by cspiel1** [comment]
`jitter_buffer_wish` is obsolete

I updated the wiki.

Your settings could be transferred to:
```
jitter_buffer_type adaptive
jitter_buffer_delay 5-10
audio_buffer_mode adaptive
audio_buffer 40-200
```

**Comment by juha-h** [comment]
Christian Spielberger writes:

> `jitter_buffer_wish` is obsolete
> 
> I updated the wiki.
> 
> Your settings could be transferred to:
> ```
> jitter_buffer_type adaptive
> jitter_buffer_delay 5-10
> audio_buffer_mode adaptive
> audio_buffer 40-200
> ```

Thank you very much.

**Pull request merged**
