### PR TITLE
uag,menu: simplify transport enable/disable and support also ws/wss

### PR DESCRIPTION
**Pull request by cspiel1**
Its better to have only one command for enabling transport. Requested by @juha-h.

Rework of: https://github.com/baresip/baresip/pull/1502

### CODE REVIEW

**Comment by juha-h** [comment]
Christian Spielberger writes:

>   * uag,menu: simplify transport enable/disable and support also
>   * ws/wss

Thanks, I did some testing and everything worked fine.

**Comment by juha-h** [comment]
Since transport enabling/disabling is global, would it make sense to have a config variable or variables to set initial values?

**Comment by cspiel1** [comment]
> Since transport enabling/disabling is global, would it make sense to have a config variable or variables to set initial values?

Yes, I also though about this. I will add a commit.

**Comment by cspiel1** [comment]
Note: added utility functions
```
void u32mask_enable(uint32_t *mask, uint8_t bit, bool enable);
bool u32mask_enabled(uint32_t *mask, uint8_t bit);
```
Can be moved to re. In next PR?

**Pull request merged**
