### PR TITLE
release v3.7.0

### PR DESCRIPTION
**Pull request by cspiel1**

### CODE REVIEW

**Comment by cspiel1** [comment]
@sreimers @juha-h  I didn't get the outcome of your discussions about the debian changelog.

 `UNRELEASED` or unstable?

**Comment by sreimers** [comment]
Unstable looks fine to me.

**Comment by juha-h** [comment]
I don't know if there was an outcome.  I just used `dch` command to create new entry and by default it produces `UNRELEASED` entry.  That could then be changed by the maintainer to something else when he/she makes the version available in a Debian distribution.

**Comment by cspiel1** [comment]
ABI version incremented, because new values added to `enum ua_event`

**Pull request merged**
