### PR TITLE
Convert FRITZ!Box XML phone book into Baresip contacts

### PR DESCRIPTION
**Pull request by robert-scheck**
As mentioned in #1370, I'm hereby proposing my simple converter for the newly introduced `tools` directory.

### CODE REVIEW

**Comment by alfredh** [comment]
thanks, great work!

perhaps also consider to add a Wiki page with some examples of how to use it.

**Comment by robert-scheck** [comment]
Done (https://github.com/baresip/baresip/wiki/Tools:-fritzbox2baresip), but I unfortunately can't push the two screenshots to the Wiki git due to lack of permissions (GitHub allows webbased edits, but seems to require repository-wide write permissions to push Wiki commits which are needed for image upload). May I provide them (< 100 KiB) simply via e-mail to you, @alfredh?

**Comment by alfredh** [comment]
sure!

**Comment by robert-scheck** [comment]
OK, I've sent them to your e-mail address mentioned in your GitHub patches.

**Comment by alfredh** [comment]
done:

```
l images/
total 328
drwxr-xr-x   7 alfredh  staff    224 May  1 10:33 .
drwxr-xr-x  43 alfredh  staff   1376 May  1 10:32 ..
-rw-r--r--   1 alfredh  staff  19185 May  1 10:32 screenshot-baresip-gtk.png
-rw-r--r--   1 alfredh  staff  17758 May  1 10:32 screenshot-baresip-startup.png
-rw-r--r--   1 alfredh  staff  28746 May  1 10:32 screenshot-baresip-vidloop.png
-rw-r--r--@  1 alfredh  staff  58689 May  1 10:33 screenshot-fritzbox2baresip-export.png
-rw-r--r--@  1 alfredh  staff  29127 May  1 10:33 screenshot-fritzbox2baresip-result.png
```

**Comment by robert-scheck** [comment]
Thank you! Wiki page looks now nicely to me.

**Pull request merged**
