### PR TITLE
gst: support blocking mode

### PR DESCRIPTION
**Pull request by cspiel1**
With blocking mode the whole audio file is read as fast as possible.

### CODE REVIEW

**Comment by alfredh** [comment]
Perhaps this API can be used to get duration:

https://gstreamer.freedesktop.org/documentation/gstreamer/gstelement.html?gi-language=c#gst_element_query_duration

**Comment by cspiel1** [comment]
I'll try this. But have to postpone this.

**Comment by cspiel1** [comment]
Next try this: https://github.com/baresip/baresip/pull/3030#issuecomment-2144310282

**Comment by cspiel1** [comment]
Will be replaced by: https://github.com/cspiel1/baresip/commit/cce853db01c2c53fe6d003827481cdf4d434f21e

**Pull request closed without merging**
