### PR TITLE
Ua select outgoing

### PR DESCRIPTION
**Pull request by cspiel1**
Automatic UA selection for SIP requests (e.g. dial command)

Based on https://github.com/baresip/baresip/pull/1207. Has to be re-based to master after merge.

### CODE REVIEW

**Comment by juha-h** [comment]
I looked at the pull request, but could not find src/ua.c changes.  Just
liked to check that backwards compatibility is preserved in API.

> -- Commit Summary --
> 
>   * menu: remove ua_next() and not use current UA for dialing
>   * menu: switch audio device over all UAs
>   * menu: switch video source apply to all uas
>   * menu: replace current UA by current call-id
>   * menu: fix gcc warning unused parameter pf
>   * menu: use print backend pointer pf correctly
>   * menu: for CALL_CLOSED clear active call id
>   * config: add default SIP transport for outgoing calls
>   * ua: automatic UA selection for SIP requests
>   * menu: use uag_find_requri() for dial command
> 
> -- File Changes --
> 
>     M docs/examples/config (1)
>     M include/baresip.h (2)
>     M modules/menu/dynamic_menu.c (73)
>     M modules/menu/menu.c (73)
>     M modules/menu/menu.h (11)
>     M modules/menu/static_menu.c (178)
>     M src/config.c (17)
>     M src/ua.c (156)

**Comment by cspiel1** [comment]
It's still a draft and contains also the commits of the PR mentioned in the description.

The commit you are looking for is:
https://github.com/baresip/baresip/pull/1217/commits/8d73f213d94cbffd7b6ebf92bea9c14c9917023f

**Comment by juha-h** [comment]
Christian Spielberger writes:

> The commit you are looking for is:
> https://github.com/baresip/baresip/pull/1217/commits/8d73f213d94cbffd7b6ebf92bea9c14c9917023f

OK, looked good to me.

**Comment by cspiel1** [comment]
Now is part of https://github.com/baresip/baresip/pull/1207.

**Pull request closed without merging**
