### PR TITLE
message: reply only once

### PR DESCRIPTION
**Pull request by cspiel1**
baresip sends a reply for a SIP MESSAGE for each message listener.

How often we process a SIP MESSAGE is not interesting for the remote who sent the MESSAGE. In our case “menu” prints the message and ctrl_tcp forwards the message.

### CODE REVIEW

**Comment by cspiel1** [comment]
@sreimers A problem with TLS?
[ RUN      ] test_message
262
tls: connect: error (r=-1, ssl_err=1)

I can't reproduce this on my dev host.

**Comment by sreimers** [comment]
Should work now (just restarted the tests), i reverted the last baresip/re change and make tls verify opt-in, until we make it configurable.

**Comment by cspiel1** [comment]
Ah, I see. I forgot to update libre. Thanks for the hint!

**Comment by cspiel1** [comment]
Should I make the PR for the accounts config?
We will have to pass it to libre somehow in sip_transp_send() and conn_send(). Do you have an suggestion?

**Comment by sreimers** [comment]
> Should I make the PR for the accounts config?

That would be nice.

> We will have to pass it to libre somehow in sip_transp_send() and conn_send(). Do you have a suggestion?

Maybe throw sip_transp_add and the `Optional transport parameters such as TLS context` https://github.com/baresip/re/blob/master/src/sip/transp.c#L1021

But I didn't look into it any further. Maybe there is a better way.

**Pull request merged**
