### PR TITLE
mixausrc: fix downsampling

### PR DESCRIPTION
**Pull request by cspiel1**
Fixes: https://github.com/baresip/baresip/issues/3049

- ptime taken from stream
- sampc, nbytes computed from ausrc sample rate
- the resampler needs maximum sampc between input/output

### CODE REVIEW

**Comment by cspiel1** [comment]
TODO:
In line 614 we need different `nbytes`. Has to be checked.
```c
else if (aubuf_cur_size(st->aubuf) >= st->nbytes) {
```
Because now it is the maximum of input/output.

**Comment by cspiel1** [comment]
@marcel-behlau-elfin please could you test this branch with your 48kHz WAV file?

```
/mixausrc_enc_start aufile /home/marcel/Documents/sip/test.wav 0 100
aufile: loading input file '/home/marcel/Documents/sip/test.wav'
aufile: /home/marcel/Documents/sip/test.wav: 48000 Hz, 1 channels, S16LE
```

**Comment by cspiel1** [comment]
I tested
- encoding mix
- decoding mix

- downsamling
  - `mixausrc: resample ausrc 48000/2 -> 16000/1`
- upsampling
  - `mixausrc: resample ausrc 8000/1 -> 16000/1`

**Comment by marcel-behlau-elfin** [comment]
Works like a charm =)

```
/mixausrc_enc_start aufile /home/marcel/Documents/sip/test.wav 0 100
aufile: loading input file '/home/marcel/Documents/sip/test.wav'
aufile: /home/marcel/Documents/sip/test.wav: 48000 Hz, 1 channels, S16LE
aufile: audio ptime=20 sampc=960
aufile: read end of file
aufile: loaded 377836 bytes
aufile: end of file00/64000 (bit/s) 
```

**Pull request merged**
