### PR TITLE
Update README.md with configuration suggestion

### PR DESCRIPTION
**Pull request by webstean**
as suggested by https://github.com/znoteer

### CODE REVIEW

**Comment by juha-h** [comment]
Andrew Webster writes:

> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/baresip/baresip/pull/1438

Typo in word Documentatin.

**Comment by cspiel1** [comment]
Please make a list and write:
```
- Configuration examples are available from the
[examples](https://github.com/baresip/baresip/tree/master/docs/examples)
￼directory.
￼- ￼Documentatin on configuring baresip can be found in the [Wiki](https://github.com/baresip/baresip/wiki/Configuration)
```

**Comment by webstean** [comment]
Updated the text, formatted and corrected the typos.

**Comment by juha-h** [comment]
I too looked at this PR and found some garbage characters in the text:
```
* Configuration examples are available from the
[examples](https://github.com/baresip/baresip/tree/master/docs/examples)
ï¿¼directory.
ï¿¼* ï¿¼Documentation on configuring baresip can be found in the [Wiki](https://github.com/baresip/baresip/wiki/Configuration).
```
I'll fix them.

**Pull request merged**
