### PR TITLE
Mixausrc

### PR DESCRIPTION
**Pull request by cspiel1**
Adds a filter that is able to mix an ausrc into the audio encode/decode stream.

### CODE REVIEW

**Comment by cspiel1** [comment]
- will test again after merge of https://github.com/baresip/baresip/pull/1157

**Comment by alfredh** [comment]
can you also add the new module here:

https://github.com/baresip/baresip/wiki/Modules

**Comment by alfredh** [comment]
thanks for your work, the module was merged.


when building on OSX I get some warnings:

```
  CC [M]  build-x86_64/modules/mixausrc/mixausrc.o
modules/mixausrc/mixausrc.c:132:18: warning: implicit conversion loses integer precision:
      'unsigned long' to 'uint32_t' (aka 'unsigned int') [-Wshorten-64-to-32]
        wishsz = wishsz * num_bytes;
               ~ ~~~~~~~^~~~~~~~~~~
modules/mixausrc/mixausrc.c:423:33: warning: implicit conversion loses integer precision: 'size_t'
      (aka 'unsigned long') to 'uint32_t' (aka 'unsigned int') [-Wshorten-64-to-32]
                fade_int16(st, af->sampv, af->sampc, dir);
                ~~~~~~~~~~                ~~~~^~~~~
modules/mixausrc/mixausrc.c:425:33: warning: implicit conversion loses integer precision: 'size_t'
      (aka 'unsigned long') to 'uint32_t' (aka 'unsigned int') [-Wshorten-64-to-32]
                fade_float(st, af->sampv, af->sampc, dir);
                ~~~~~~~~~~                ~~~~^~~~~
modules/mixausrc/mixausrc.c:454:32: warning: implicit conversion loses integer precision: 'size_t'
      (aka 'unsigned long') to 'uint32_t' (aka 'unsigned int') [-Wshorten-64-to-32]
                mix_int16(st, af->sampv, af->sampc);
                ~~~~~~~~~                ~~~~^~~~~
modules/mixausrc/mixausrc.c:456:32: warning: implicit conversion loses integer precision: 'size_t'
      (aka 'unsigned long') to 'uint32_t' (aka 'unsigned int') [-Wshorten-64-to-32]
                mix_float(st, af->sampv, af->sampc);
                ~~~~~~~~~                ~~~~^~~~~
modules/mixausrc/mixausrc.c:473:56: warning: implicit conversion loses integer precision:
      'unsigned long' to 'uint32_t' (aka 'unsigned int') [-Wshorten-64-to-32]
                st->ausrc_prm.ptime = n * 1000 / st->ausrc_prm.srate /
                                    ~ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
modules/mixausrc/mixausrc.c:477:18: warning: implicit conversion loses integer precision:
      'unsigned long' to 'uint32_t' (aka 'unsigned int') [-Wshorten-64-to-32]
                st->n_fade = n * pnbr;
                           ~ ~~^~~~~~
7 warnings generated.

```

**Comment by cspiel1** [comment]
Ok, I will fix these warnings

Alfred E. Heggestad <notifications@github.com> schrieb am Mo., 28. Dez.
2020, 11:20:

**Pull request merged**
