### PR TITLE
test/call.c: extend test_call_hold_resume

### PR DESCRIPTION
**Pull request by maximilianfridrich**
Updates the `test_call_hold_resume` test by initiating a call and offering the streams as `sendonly`. The test verifies that this does not trigger an `UA_EVENT_CALL_HOLD` on the receiving side of this offer. It then does a few hold/resumes from both sides and verifies the events `UA_EVENT_CALL_HOLD` and `UA_EVENT_CALL_RESUME` are only triggered when they should.

### CODE REVIEW

**Comment by cspiel1** [comment]
Looks good to me.

**Comment by cspiel1** [comment]
In a future PR we should make the counter `n_...` to be integer instead of uint.
`-1` means do not compare the value.

**Comment by alfredh** [comment]
This test became unstable after the merge:

https://github.com/baresip/baresip/actions/runs/6783024753/job/18436437302

can you please investigate ?

**Comment by maximilianfridrich** [comment]
@alfredh I'm not sure if I'm interpreting the linked output correctly, but it looks like it found a data race when running `test_call_100rel_audio`. I don't know how I could've caused a data race with this change - I didn't touch `test_call_100rel_audio`.

**Comment by cspiel1** [comment]
I will have a look.

**Comment by cspiel1** [comment]
> This test became unstable after the merge:
> 
> https://github.com/baresip/baresip/actions/runs/6783024753/job/18436437302
> 
> can you please investigate ?

This https://github.com/baresip/baresip/pull/2809 should directly solve the sanitizer warning.

**Pull request merged**
