### PR TITLE
cmake,debian: use dh-cmake

### PR DESCRIPTION
**Pull request by sreimers**

### CODE REVIEW

**Comment by alfredh** [comment]
Should we deprecate/remove the old "GNU Make" build-system ?

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> Should we deprecate/remove the old "GNU Make" build-system ?

My Android libbaresip build is still using make.  So perhaps deprecate
now and remove after a few weeks.

**Comment by sreimers** [comment]
I think this is the last dependency. So we can deprecate GNU Make.

**Comment by juha-h** [comment]
I tried to replace my NDK re make build
```
libre.a: Makefile
	make distclean -C re
	PATH=$(PATH) RANLIB=$(RANLIB) AR=$(AR) CC=$(CC) make $@ -C re $(COMMON_FLAGS)
```
with cmake build:
```
libre.a: Makefile
	make distclean -C re
	cd re && rm -rf build && mkdir build && cd build && \
	cmake .. $(CMAKE_ANDROID_FLAGS) && \
	PATH=$(PATH) RANLIB=$(RANLIB) AR=$(AR) CC="$(CC) --sysroot $(SYSROOT)" make $@ -C re $(COMMON_FLAGS)
```
and cmake failed like this:
```
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR) 
...
Please set them or make sure they are set and tested correctly in the CMake files:
/usr/src/libbaresip-android/re/OPENSSL_INCLUDE_DIR
   used as include directory in directory /usr/src/libbaresip-android/re
```

**Comment by juha-h** [comment]
What is `system variable OPENSSL_ROOT_DIR`?  I tried to set it in cmake command
```
cmake .. $(CMAKE_ANDROID_FLAGS) -DOPENSSL_ROOT_DIR=/usr/src/libbaresip/openssl && \
```
but that didn't help.  Why there is no problem in finding openssl when make is used?

**Comment by juha-h** [comment]
Where is `FIndOPENSSL.cmake`?

**Comment by alfredh** [comment]
you can use this as example:

```
libre.a: Makefile
	@rm -f re/libre.*
	cmake \
		-S re \
		-B re/build \
		-DCMAKE_TOOLCHAIN_FILE=$(PWD)/cmake/mingw-w64-x86_64.cmake \
		-DOPENSSL_ROOT_DIR=$(PWD)/openssl
	cmake --build re/build --target re -j4
```



https://github.com/baresip/baresip-win32/blob/main/Makefile


when cross compiling it is smart to use `CMAKE_TOOLCHAIN_FILE`

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> when cross compiling it is smart to use `CMAKE_TOOLCHAIN_FILE`

I am using it:

CMAKE_TOOLCHAIN_FILE := $(NDK_PATH)/build/cmake/android.toolchain.cmake
...
CMAKE_ANDROID_FLAGS := \
	-DANDROID=ON \
	-DANDROID_PLATFORM=$(API_LEVEL) \
	-DCMAKE_SYSTEM_NAME=Android \
	-DCMAKE_SYSTEM_VERSION=$(API_LEVEL) \
	-DCMAKE_TOOLCHAIN_FILE=$(CMAKE_TOOLCHAIN_FILE) \
	-DANDROID_ABI=$(ANDROID_TARGET_ARCH) \
	-DCMAKE_ANDROID_ARCH_ABI=$(ANDROID_TARGET_ARCH) \
	-DCMAKE_SKIP_INSTALL_RPATH=ON \
	-DCMAKE_C_COMPILER=$(CC) \
	-DCMAKE_CXX_COMPILER=$(CXX) \
	-DCMAKE_POSITION_INDEPENDENT_CODE=ON
...
libre.a
    ...
    cmake .. $(CMAKE_ANDROID_FLAGS) && \

**Comment by sreimers** [comment]
> Where is `FindOPENSSL.cmake`?

Is provided by cmake directly, since a common one. https://cmake.org/cmake/help/v3.23/module/FindOpenSSL.html

Maybe setting a root path helps also:

`CMAKE_FIND_ROOT_PATH`

In my projects I create a `third_party` folder with `include` and `lib` subfolders and copy the libs and headers like `libcrypto.a` there.

So I can use simply:

```cmake
set(CMAKE_FIND_ROOT_PATH ${CMAKE_CURRENT_SOURCE_DIR}/third_party)
```

**Comment by sreimers** [comment]
With:

```cmake
  set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
  set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
  set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```
You can control if only root path should be used (useful for cross compile) or system/host libs too. The root path gets prioritized anyways.

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> > Where is `FindOPENSSL.cmake`?
> 
> Is provided by cmake directly, since a common one. https://cmake.org/cmake/help/v3.23/module/FindOpenSSL.html

OK, but is it only looking for .so files.  I only have these:

/usr/src/libbaresip-android$ ls openssl/lib
libcrypto.a   libcrypto.pc  libssl.a      libssl.pc

**Comment by juha-h** [comment]
I tried like this:
```
libre.a: Makefile
	rm -f re/libre.* && rm -r re/build && \
	cmake \
		-S re \
		-B re/build \
		$(CMAKE_ANDROID_FLAGS) -DOPENSSL_ROOT_DIR=/usr/src/libbaresip-android/openssl \
		-DOPENSSL_USE_STATIC_LIBS=ON
```
`OPENSSL_ROOT_DIR` is correct:
```
$ ls /usr/src/libbaresip-android/openssl
ACKNOWLEDGEMENTS  config.com	   engines/   libcrypto.a   ms/		   openssl.pc	       tools/
apps/		  configdata.pm*   e_os.h     libcrypto.pc  NEWS	   os-dep/	       util/
appveyor.yml	  Configurations/  external/  libcrypto.so  NOTES.ANDROID  pyca-cryptography/  VMS/
AUTHORS		  Configure*	   FAQ	      libssl.a	    NOTES.DJGPP    README
boringssl/	  CONTRIBUTING	   fuzz/      libssl.pc     NOTES.PERL	   README.ENGINE
build.info	  crypto/	   include/   libssl.so     NOTES.UNIX	   README.FIPS
CHANGES		  demos/	   INSTALL    LICENSE	    NOTES.VMS	   ssl/
config*		  doc/		   krb5/      Makefile	    NOTES.WIN	   test/
```
It has .a files and include sub-dir.

So why is openssl not found:
```
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY OPENSSL_INCLUDE_DIR) 
```

**Comment by sreimers** [comment]
Is `OPENSSL_ROOT_DIR` within `CMAKE_FIND_ROOT_PATH` ? Maybe `CMAKE_FIND_ROOT_PATH` is set by the toolchain file.

**Comment by juha-h** [comment]
I have not set CMAKE_FIND_ROOT_PATH and checked that CMAKE_FIND_ROOT_PATH is not set in 
```
-DCMAKE_TOOLCHAIN_FILE=/opt/Android/ndk/25.1.8937393/build/cmake/android.toolchain.cmake
```
I suspect that since my openssl build only createa .a libs, cmake does not find them.  This is because
```
New in version 3.4: Set OPENSSL_USE_STATIC_LIBS to TRUE to look for static libraries.
```
and cmake version in Debian 11 is  3.24.1.

**Comment by juha-h** [comment]
Is it possible to override the built-in FindOPENSSL.cmake?

**Comment by juha-h** [comment]
I made some progress by explicitly setting:
```
	-DOPENSSL_CRYPTO_LIBRARY=$(OUTPUT_DIR)/openssl/lib/$(ANDROID_TARGET_ARCH)/libcrypto.a \
	-DOPENSSL_SSL_LIBRARY=$(OUTPUT_DIR)/openssl/lib/$(ANDROID_TARGET_ARCH)/libssl.a \
```
Then OpenSSL was found:
```
-- Found OpenSSL: /usr/src/baresip-studio/distribution/openssl/lib/arm64-v8a/libcrypto.a (found version "1.1.1m")
```
BUT:
```
-- Configuring done
CMake Error at CMakeLists.txt:564 (target_link_libraries):
  Target "re-shared" links to:

    OpenSSL::SSL

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```
As mentioned, I'm only building openssl static libs (I have --disable-shared in openssl build).  So looks like re/CMakeLists.txt needs to be fixed to allow that.

**Comment by sreimers** [comment]
FindOPENSSL.cmake should work fine with static builds, used this many times. OPENSSL_USE_STATIC_LIBS I think is only needed if you have both, static and shared libs and want to prioritize.

You need something like this, since the android toolchain file overrides system folders.

```cmake
set(OPENSSL_ROOT_DIR "/path/to/openssl/for/android")
list(APPEND CMAKE_FIND_ROOT_PATH "${OPENSSL_ROOT_DIR}")
```

**Comment by juha-h** [comment]
The problem was that `-DOPENSSL_SSL_LIBRARY=$(OUTPUT_DIR)/openssl/lib/$(ANDROID_TARGET_ARCH)/libssl.a` was not in cmake when I made the test.  Now when it is, the build worked:
```
cd re && \
	rm -rf build && mkdir build && cd build && \
	cmake .. \
		$(CMAKE_ANDROID_FLAGS) \
		-DOPENSSL_CRYPTO_LIBRARY=$(OUTPUT_DIR)/openssl/lib/$(ANDROID_TARGET_ARCH)/libcrypto.a \
		-DOPENSSL_SSL_LIBRARY=$(OUTPUT_DIR)/openssl/lib/$(ANDROID_TARGET_ARCH)/libssl.a \
		-DOPENSSL_INCLUDE_DIR=$(PWD)/openssl/include && \
	CC="$(CC) --sysroot $(SYSROOT)" PATH=$(PATH) VERBOSE=1 make
```
But based on this experience, by impression of cmake is very low.

**Comment by juha-h** [comment]
I tried rem next with this:
```
librem.a:
	cd rem && \
	rm -rf build && mkdir build && cd build && \
	cmake .. \
		$(CMAKE_ANDROID_FLAGS) \
		-Dre_DIR=$(PWD)/re/cmake \
		-DRE_LIBRARY=$(PWD)/re/build \
		-DRE_INCLUDE_DIR=$(PWD)/re/include \
		-DOPENSSL_INCLUDE_DIR=$(PWD)/openssl/include && \
	CC="$(CC) --sysroot $(SYSROOT)" PATH=$(PATH) VERBOSE=1 make
```
Everything was found, but then came these:
```
-- Configuring done
CMake Warning at CMakeLists.txt:160 (target_link_libraries):
  Target "rem-shared" requests linking to directory
  "/usr/src/libbaresip-android/re/build".  Targets may link only to
  libraries.  CMake is dropping the item.

CMake Warning at CMakeLists.txt:173 (target_link_libraries):
  Target "rem" requests linking to directory
  "/usr/src/libbaresip-android/re/build".  Targets may link only to
  libraries.  CMake is dropping the item.
```
Compilation worked fine, but linking failed:
```
make[3]: Entering directory '/usr/src/libbaresip-android/rem/build'
[ 96%] Linking C shared library librem.so
/usr/bin/cmake -E cmake_link_script CMakeFiles/rem-shared.dir/link.txt --verbose=1
/opt/Android/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=aarch64-none-linux-android21 --sysroot=/opt/Android/ndk/25.1.8937393/toolchains/llvm/prebuilt/linux-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security  -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Wl,--gc-sections -Wl,--no-undefined -Qunused-arguments  -shared -Wl,-soname,librem.so -o librem.so "CMakeFiles/rem-objs.dir/src/aac/aac.c.o" "CMakeFiles/rem-objs.dir/src/au/fmt.c.o" "CMakeFiles/rem-objs.dir/src/au/util.c.o" "CMakeFiles/rem-objs.dir/src/aubuf/aubuf.c.o" "CMakeFiles/rem-objs.dir/src/aubuf/ajb.c.o" "CMakeFiles/rem-objs.dir/src/auconv/auconv.c.o" "CMakeFiles/rem-objs.dir/src/aufile/aufile.c.o" "CMakeFiles/rem-objs.dir/src/aufile/wave.c.o" "CMakeFiles/rem-objs.dir/src/auframe/auframe.c.o" "CMakeFiles/rem-objs.dir/src/aulevel/aulevel.c.o" "CMakeFiles/rem-objs.dir/src/aumix/aumix.c.o" "CMakeFiles/rem-objs.dir/src/auresamp/resamp.c.o" "CMakeFiles/rem-objs.dir/src/autone/tone.c.o" "CMakeFiles/rem-objs.dir/src/avc/config.c.o" "CMakeFiles/rem-objs.dir/src/dtmf/dec.c.o" "CMakeFiles/rem-objs.dir/src/fir/fir.c.o" "CMakeFiles/rem-objs.dir/src/g711/g711.c.o" "CMakeFiles/rem-objs.dir/src/goertzel/goertzel.c.o" "CMakeFiles/rem-objs.dir/src/vid/draw.c.o" "CMakeFiles/rem-objs.dir/src/vid/fmt.c.o" "CMakeFiles/rem-objs.dir/src/vid/frame.c.o" "CMakeFiles/rem-objs.dir/src/vidconv/vconv.c.o" "CMakeFiles/rem-objs.dir/src/vidmix/vidmix.c.o"  -lm -pthread -latomic -lm 
ld: error: undefined symbol: mem_zalloc
```
mem_zallow was just the first symbol not found.

**Comment by juha-h** [comment]
OK, got it fixed by using libre.a in
```
		-DRE_LIBRARY=$(PWD)/re/build/libre.a \
```

**Comment by juha-h** [comment]
After libre.a and librem.a cmake builds worked, I tried to build libbaresip.a (start with only module g177):
```
libbaresip: Makefile librem.a
	cd baresip && \
	rm -rf build && \
	cmake -B build \
		$(CMAKE_ANDROID_FLAGS) \
		-DSTATIC=ON \
		-Dre_DIR=$(PWD)/re/cmake \
		-DRE_LIBRARY=$(PWD)/re/build/libre.a \
		-DRE_INCLUDE_DIR=$(PWD)/re/include \
		-DREM_LIBRARY=$(PWD)/rem/build/librem.a \
		-DREM_INCLUDE_DIR=$(PWD)/rem/include \
		-DOPENSSL_INCLUDE_DIR=$(PWD)/openssl/include \
		-DCMAKE_C_COMPILER="clang" \
		-DCMAKE_CXX_COMPILER="clang++" \
		-DMODULES=g711 && \
	 cmake --build build -j
```
Compile and linking worked:
```
[ 73%] Linking C static library libbaresip.a
```
Then it started to make webrtc and test (which failed). 

How to tell cmake that I only want to build libbaresip.a?  Checked baresip README.md, but it was not there.

**Comment by sreimers** [comment]
Maybe we should open a new discussion.

**Comment by juha-h** [comment]
Yes, I agree.  I'll do that.

**Pull request merged**
