### PR TITLE
autotest: add a module for automatic call testing

### PR DESCRIPTION
**Pull request by cspiel1**
* Supports automatic repeated dialing and hangup via timers.
 * The commands for dialing and hangup can be specified by means of the registered commands.

### CODE REVIEW

**Comment by alfredh** [comment]
I think we should discuss putting features like this outside the baresip tree.
For example a new project `baresip-tools` or `baresip-apps` can be created.
This project can use the libbaresip api.

Some other modules that fits into this category:

* auloop
* vidloop

The reason is that the number of modules is growing quite high.
For a new enduser it can be quite challenging to figure out which module to use or not.

this is just an idea for now, feel free to discuss :)

apart from this comment, the code in the PR looks fine to me.

**Comment by cspiel1** [comment]
I like this idea. You mean a new repository github.com/baresip, right? Do you want to create such a new repo?

**Comment by alfredh** [comment]
something like this:

```
github.com/baresip/baresip-apps
```

the binaries can include auloop, vidloop, autotest and more.
the binaries will use the public libbaresip api.

**Comment by cspiel1** [comment]
Should I create this?

- Named: `baresip-app`
- Makefile similar to baresip that includes re.mk?
- a first simple github workflow

**Comment by alfredh** [comment]
https://github.com/baresip/baresip-apps

yes, please move the autotest module to this new baresip-apps repo.

**Comment by cspiel1** [comment]
Replaced by https://github.com/baresip/baresip-apps/pull/1

**Pull request closed without merging**
