### PR TITLE
Auplay use auframe

### PR DESCRIPTION
**Pull request by alfredh**

### CODE REVIEW

**Comment by alfredh** [comment]
this PR changes the auplay to use `struct auframe`

with this change, the frame format and timestamp can now be passed to/from
core and auplay module.

current status:

```
module:		upd:	alloc:	test:
------		---	-----	----

alsa		ok	yes	ok
aubridge	ok	yes	ok
audiounit	ok	-	ok
aufile		ok	yes	ok
coreaudio	ok	-	ok
i2s		-	yes	-
jack		ok	yes	-
opensles	-	yes	-
oss		ok	yes	-
portaudio	ok	-	-
pulse		ok	yes	-
sndio		ok	yes	-
winwave		ok	-	ok

test_mock	ok	yes	ok
```

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> this PR changes the auplay to use `struct auframe`
> 
> with this change, the frame format and timestamp can now be passed to/from
> core and auplay module.
> 
> current status:
> 
> ```
> module:		upd:	alloc:	test:
> ------		---	-----	----
...
> opensles	-	yes	-
> ```

I'm using opensles module in my Android app.  Is this change backwards
compatible or is there need some changes in the app?

**Comment by alfredh** [comment]
this is the main change:

```diff
-typedef void (auplay_write_h)(void *sampv, size_t sampc, void *arg);
+typedef void (auplay_write_h)(struct auframe *af, void *arg);
```

so the opensles module has to be updated.

this should not affect the application, unless it is using this api

**Comment by alfredh** [comment]
merged to master; please test that opensles compiles and works

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> merged to master; please test that opensles compiles and works

Compiled and worked fine, thanks.

**Pull request merged**
