### PR TITLE
Added mwi module cmake build

### PR DESCRIPTION
**Pull request by juha-h**

### CODE REVIEW

**Comment by juha-h** [comment]
I have no clue why MinGW-w64 Test failed.

**Comment by sreimers** [comment]
Yes nothing todo with this PR, we have still a heap-buffer-overflow in prack_handler. #1988

**Comment by alfredh** [comment]
Perhaps run selftest with verbose logging so we can see which test failed:

```
./selftest -v
```

**Comment by juha-h** [comment]
Can't find selftest program, but looks like the problem is now solved, since all checks have passed.

**Pull request merged**
