### PR TITLE
pipewire: add pipewire module

### PR DESCRIPTION
**Pull request by cspiel1**
- a reduction of the audio latency and
- more stability against software jitter

A first version, experimental

### CODE REVIEW

**Comment by alfredh** [comment]
what is Pipewire and why is it needed ?

**Comment by cspiel1** [comment]
> what is Pipewire and why is it needed ?

We think it is the future. Please read "Motivation" at https://docs.pipewire.org/page_overview.html !

E.g. on Ubuntu it will replace pulseaudio soon.
- https://ubuntuhandbook.org/index.php/2022/04/pipewire-replace-pulseaudio-ubuntu-2204/
- https://www.omgubuntu.co.uk/2022/05/ubuntu-22-10-makes-pipewire-default

**Comment by robert-scheck** [comment]
> E.g. on Ubuntu it will replace pulseaudio soon.

Similar situation at Fedora (and thus CentOS/RHEL): https://fedoraproject.org/wiki/Changes/DefaultPipeWire

**Comment by RobertMi21** [comment]
I already replaced pulseaudio with pipewire on my development machine. Works great :-) And a great first benefit: one can activate echo canceling out of the box (as an example) :-)

One remark/question:

we need a way to select an audio device or did I miss that?

**Comment by cspiel1** [comment]
By means of pipewire we except to achieve

- a reduction of the audio latency and
- more stability against software jitter

on our embedded devices.

**Comment by cspiel1** [comment]
> we need a way to select an audio device or did I miss that?

This is coming soon. The next commit.

**Comment by alfredh** [comment]
my proposal would be to add it to the `baresip-apps` staging project, and ask people
for testing and feedback.

The Linux audio world is a complete mess, there is Alsa, Pulse, Jack etc.
Why should all applications have to rewritten every time there is a new Audio subsystem ?

Using pipewire daemon is not the same as using pipewire API, since they support
other APIs like ALSA and Pulse. It is possible for a legacy application to use
e.g. ALSA api and Pipewire daemon.

**Comment by cspiel1** [comment]
pipewire is meant to combine the benefits of pulseaudio and jack. Since some distributions already decided to switch to Pipewire as default audio daemon we think that it will not be replaced in the next years.

This is not an application module and so it fits better into the baresip repository. We should keep `alsa` as default audio module. After a testing phase of e.g. one year we should mark the `pulse` module as deprecated. Then `pipewire` should become the suggested module for linux hosts and embedded systems. Only for very lightweight systems, where no `pipewire` or `pulseaudio` is available `alsa` should be used directly.

But if you really don't want to have it here, then I'll move it to `baresip-apps`. Just let me know how you decide!

**Comment by cspiel1** [comment]
Maybe someone else could try this module before we merge it. E.g. @robert-scheck ?
I try to motivate some of my colleagues to do in on their dev hosts. Unfortunately currently we have no pipewire build for our embedded devices.

**Comment by robert-scheck** [comment]
Personally, I'm still on RHEL 7, but a hardware rollover in the next months will bring me to RHEL 9. I'll ask some people with RHEL 9 or a Fedora in the meantime to give it a try.

**Review by robert-scheck — COMMENTED** [review]
1. Trying to build the changes from this pull request fails on Fedora Rawhide (PipeWire 0.3.66) like this:

```
In file included from /usr/include/pipewire-0.3/pipewire/properties.h:35,
                 from /usr/include/pipewire-0.3/pipewire/core.h:87,
                 from /usr/include/pipewire-0.3/pipewire/context.h:67,
                 from /usr/include/pipewire-0.3/pipewire/protocol.h:46,
                 from /usr/include/pipewire-0.3/pipewire/proxy.h:108,
                 from /usr/include/pipewire-0.3/pipewire/client.h:35,
                 from /usr/include/pipewire-0.3/pipewire/pipewire.h:35,
                 from /builddir/build/BUILD/baresip-2.12.0/modules/pipewire/playback.c:13:
/usr/include/spa-0.2/spa/utils/string.h: In function 'spa_strtof':
/usr/include/spa-0.2/spa/utils/string.h:279:16: error: unknown type name 'locale_t'
  279 |         static locale_t locale = NULL;
      |                ^~~~~~~~
/usr/include/spa-0.2/spa/utils/string.h:279:34: warning: initialization of 'int' from 'void *' makes integer from pointer without a cast [-Wint-conversion]
  279 |         static locale_t locale = NULL;
      |                                  ^~~~
/usr/include/spa-0.2/spa/utils/string.h:280:9: error: unknown type name 'locale_t'; did you mean 'socklen_t'?
  280 |         locale_t prev;
      |         ^~~~~~~~
      |         socklen_t
In file included from /usr/include/spa-0.2/spa/pod/pod.h:32,
                 from /usr/include/spa-0.2/spa/pod/iter.h:35,
                 from /usr/include/spa-0.2/spa/pod/parser.h:35,
                 from /usr/include/spa-0.2/spa/param/audio/format-utils.h:32,
                 from /builddir/build/BUILD/baresip-2.12.0/modules/pipewire/playback.c:12:
/usr/include/spa-0.2/spa/utils/string.h:284:33: warning: comparison between pointer and integer
  284 |         if (SPA_UNLIKELY(locale == NULL))
      |                                 ^~
/usr/include/spa-0.2/spa/utils/defs.h:292:46: note: in definition of macro 'SPA_UNLIKELY'
  292 | #define SPA_UNLIKELY(x) (__builtin_expect(!!(x),0))
      |                                              ^
/usr/include/spa-0.2/spa/utils/string.h:285:26: warning: implicit declaration of function 'newlocale'; did you mean 'setlocale'? [-Wimplicit-function-declaration]
  285 |                 locale = newlocale(LC_ALL_MASK, "C", NULL);
      |                          ^~~~~~~~~
      |                          setlocale
/usr/include/spa-0.2/spa/utils/string.h:285:26: warning: nested extern declaration of 'newlocale' [-Wnested-externs]
/usr/include/spa-0.2/spa/utils/string.h:285:36: error: 'LC_ALL_MASK' undeclared (first use in this function); did you mean 'RE_ALIGN_MASK'?
  285 |                 locale = newlocale(LC_ALL_MASK, "C", NULL);
      |                                    ^~~~~~~~~~~
      |                                    RE_ALIGN_MASK
/usr/include/spa-0.2/spa/utils/string.h:285:36: note: each undeclared identifier is reported only once for each function it appears in
/usr/include/spa-0.2/spa/utils/string.h:286:16: warning: implicit declaration of function 'uselocale'; did you mean 'setlocale'? [-Wimplicit-function-declaration]
  286 |         prev = uselocale(locale);
      |                ^~~~~~~~~
      |                setlocale
/usr/include/spa-0.2/spa/utils/string.h:286:16: warning: nested extern declaration of 'uselocale' [-Wnested-externs]
/usr/include/spa-0.2/spa/utils/string.h: In function 'spa_strtod':
/usr/include/spa-0.2/spa/utils/string.h:329:16: error: unknown type name 'locale_t'
  329 |         static locale_t locale = NULL;
      |                ^~~~~~~~
/usr/include/spa-0.2/spa/utils/string.h:329:34: warning: initialization of 'int' from 'void *' makes integer from pointer without a cast [-Wint-conversion]
  329 |         static locale_t locale = NULL;
      |                                  ^~~~
/usr/include/spa-0.2/spa/utils/string.h:330:9: error: unknown type name 'locale_t'; did you mean 'socklen_t'?
  330 |         locale_t prev;
      |         ^~~~~~~~
      |         socklen_t
/usr/include/spa-0.2/spa/utils/string.h:334:33: warning: comparison between pointer and integer
  334 |         if (SPA_UNLIKELY(locale == NULL))
      |                                 ^~
/usr/include/spa-0.2/spa/utils/defs.h:292:46: note: in definition of macro 'SPA_UNLIKELY'
  292 | #define SPA_UNLIKELY(x) (__builtin_expect(!!(x),0))
      |                                              ^
/usr/include/spa-0.2/spa/utils/string.h:335:36: error: 'LC_ALL_MASK' undeclared (first use in this function); did you mean 'RE_ALIGN_MASK'?
  335 |                 locale = newlocale(LC_ALL_MASK, "C", NULL);
      |                                    ^~~~~~~~~~~
      |                                    RE_ALIGN_MASK
In file included from /usr/include/pipewire-0.3/pipewire/properties.h:35,
                 from /usr/include/pipewire-0.3/pipewire/core.h:87,
                 from /usr/include/pipewire-0.3/pipewire/context.h:67,
                 from /usr/include/pipewire-0.3/pipewire/protocol.h:46,
                 from /usr/include/pipewire-0.3/pipewire/proxy.h:108,
                 from /usr/include/pipewire-0.3/pipewire/client.h:35,
                 from /usr/include/pipewire-0.3/pipewire/pipewire.h:35,
                 from /builddir/build/BUILD/baresip-2.12.0/modules/pipewire/capture.c:13:
/usr/include/spa-0.2/spa/utils/string.h: In function 'spa_strtof':
/usr/include/spa-0.2/spa/utils/string.h:279:16: error: unknown type name 'locale_t'
  279 |         static locale_t locale = NULL;
      |                ^~~~~~~~
/usr/include/spa-0.2/spa/utils/string.h:279:34: warning: initialization of 'int' from 'void *' makes integer from pointer without a cast [-Wint-conversion]
  279 |         static locale_t locale = NULL;
      |                                  ^~~~
/usr/include/spa-0.2/spa/utils/string.h:280:9: error: unknown type name 'locale_t'; did you mean 'socklen_t'?
  280 |         locale_t prev;
      |         ^~~~~~~~
      |         socklen_t
In file included from /usr/include/spa-0.2/spa/pod/pod.h:32,
                 from /usr/include/spa-0.2/spa/pod/iter.h:35,
                 from /usr/include/spa-0.2/spa/pod/parser.h:35,
                 from /usr/include/spa-0.2/spa/param/audio/format-utils.h:32,
                 from /builddir/build/BUILD/baresip-2.12.0/modules/pipewire/capture.c:12:
/usr/include/spa-0.2/spa/utils/string.h:284:33: warning: comparison between pointer and integer
  284 |         if (SPA_UNLIKELY(locale == NULL))
      |                                 ^~
/usr/include/spa-0.2/spa/utils/defs.h:292:46: note: in definition of macro 'SPA_UNLIKELY'
  292 | #define SPA_UNLIKELY(x) (__builtin_expect(!!(x),0))
      |                                              ^
/usr/include/spa-0.2/spa/utils/string.h:285:26: warning: implicit declaration of function 'newlocale'; did you mean 'setlocale'? [-Wimplicit-function-declaration]
  285 |                 locale = newlocale(LC_ALL_MASK, "C", NULL);
      |                          ^~~~~~~~~
      |                          setlocale
/usr/include/spa-0.2/spa/utils/string.h:285:26: warning: nested extern declaration of 'newlocale' [-Wnested-externs]
/usr/include/spa-0.2/spa/utils/string.h:285:36: error: 'LC_ALL_MASK' undeclared (first use in this function); did you mean 'RE_ALIGN_MASK'?
  285 |                 locale = newlocale(LC_ALL_MASK, "C", NULL);
      |                                    ^~~~~~~~~~~
      |                                    RE_ALIGN_MASK
/usr/include/spa-0.2/spa/utils/string.h:285:36: note: each undeclared identifier is reported only once for each function it appears in
/usr/include/spa-0.2/spa/utils/string.h:286:16: warning: implicit declaration of function 'uselocale'; did you mean 'setlocale'? [-Wimplicit-function-declaration]
  286 |         prev = uselocale(locale);
      |                ^~~~~~~~~
      |                setlocale
/usr/include/spa-0.2/spa/utils/string.h:286:16: warning: nested extern declaration of 'uselocale' [-Wnested-externs]
/usr/include/spa-0.2/spa/utils/string.h: In function 'spa_strtod':
/usr/include/spa-0.2/spa/utils/string.h:329:16: error: unknown type name 'locale_t'
  329 |         static locale_t locale = NULL;
      |                ^~~~~~~~
/usr/include/spa-0.2/spa/utils/string.h:329:34: warning: initialization of 'int' from 'void *' makes integer from pointer without a cast [-Wint-conversion]
  329 |         static locale_t locale = NULL;
      |                                  ^~~~
/usr/include/spa-0.2/spa/utils/string.h:330:9: error: unknown type name 'locale_t'; did you mean 'socklen_t'?
  330 |         locale_t prev;
      |         ^~~~~~~~
      |         socklen_t
/usr/include/spa-0.2/spa/utils/string.h:334:33: warning: comparison between pointer and integer
  334 |         if (SPA_UNLIKELY(locale == NULL))
      |                                 ^~
/usr/include/spa-0.2/spa/utils/defs.h:292:46: note: in definition of macro 'SPA_UNLIKELY'
  292 | #define SPA_UNLIKELY(x) (__builtin_expect(!!(x),0))
      |                                              ^
gmake[2]: *** [modules/pipewire/CMakeFiles/pipewire.dir/build.make:93: modules/pipewire/CMakeFiles/pipewire.dir/playback.c.o] Error 1
/usr/include/spa-0.2/spa/utils/string.h:335:36: error: 'LC_ALL_MASK' undeclared (first use in this function); did you mean 'RE_ALIGN_MASK'?
  335 |                 locale = newlocale(LC_ALL_MASK, "C", NULL);
      |                                    ^~~~~~~~~~~
      |                                    RE_ALIGN_MASK
```

I was able to build it successfully once I passed `-D_XOPEN_SOURCE=700` to `target_compile_options()` in `modules/pipewire/CMakeLists.txt`. When looking to https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2390 and https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2997, this seems to be an unresolved issue in PipeWire.

However, a subsequent rebuild with this change applied worked flawlessly on Fedora 37 – and a 1+ hour phone call (inbound) using the PipeWire module worked as expected, too.

2. https://github.com/cspiel1/baresip/pull/1 would make the PipeWire support from my perspective more complete for downstream usage, like at Fedora.

3. Trying to build the changes from this pull request (unchanged, so without `-D_XOPEN_SOURCE=700`) fails on CentOS Stream 8 (PipeWire 0.3.6) like this:

```
/builddir/build/BUILD/baresip-2.12.0/modules/pipewire/playback.c:89:10: error: 'PW_KEY_TARGET_OBJECT' undeclared (first use in this function); did you mean 'PW_KEY_PORT_NAME'?
          PW_KEY_TARGET_OBJECT, dev,
          ^~~~~~~~~~~~~~~~~~~~
          PW_KEY_PORT_NAME
```

and

```
/builddir/build/BUILD/baresip-2.12.0/modules/pipewire/capture.c:93:10: error: 'PW_KEY_TARGET_OBJECT' undeclared (first use in this function); did you mean 'PW_KEY_PORT_NAME'?
          PW_KEY_TARGET_OBJECT, dev,
          ^~~~~~~~~~~~~~~~~~~~
          PW_KEY_PORT_NAME
/builddir/build/BUILD/baresip-2.12.0/modules/pipewire/capture.c:93:10: note: each undeclared identifier is reported only once for each function it appears in
/builddir/build/BUILD/baresip-2.12.0/modules/pipewire/capture.c: In function 'on_process':
/builddir/build/BUILD/baresip-2.12.0/modules/pipewire/capture.c:162:10: warning: implicit declaration of function 'SPA_PTROFF'; did you mean 'SPA_PTRDIFF'? [-Wimplicit-function-declaration]
  sampv = SPA_PTROFF(d->data, offs, void);
          ^~~~~~~~~~
          SPA_PTRDIFF
/builddir/build/BUILD/baresip-2.12.0/modules/pipewire/capture.c:162:10: warning: nested extern declaration of 'SPA_PTROFF' [-Wnested-externs]
/builddir/build/BUILD/baresip-2.12.0/modules/pipewire/capture.c:162:36: error: expected expression before 'void'
  sampv = SPA_PTROFF(d->data, offs, void);
                                    ^~~~
```

**Comment by cspiel1** [comment]
I re-based this branch onto main without any changes.

**Comment by cspiel1** [comment]
`PW_KEY_TARGET_OBJECT` is defined in pipewire 0.3.48.
Same in 0.3.66:
```
./src/pipewire/keys.h:341:#define PW_KEY_TARGET_OBJECT		"target.object"
```
Is something missing? I see that `keys.h` is included in `pipewire.h`.

**Comment by cspiel1** [comment]
I am not sure with `-D_XOPEN_SOURCE=700`. Should we set this in modules/pipewire/CMakeLists.txt ?

**Comment by robert-scheck** [comment]
> Is something missing? I see that `keys.h` is included in `pipewire.h`.

CentOS Stream 8 has PipeWire 0.3.6.

> I am not sure with `-D_XOPEN_SOURCE=700`. Should we set this in modules/pipewire/CMakeLists.txt ?

Honestly, I have no idea what's best.

**Comment by robert-scheck** [comment]
> This is quite old, from 2020. `PW_KEY_TARGET_OBJECT` isn't defined there. I would suggest that we should support pipewire >= 0.3.48. This is what I tested and it works. Here the target sound device selection is affected. And we need the device selection for baresip.

I see. Well, any chance for pipewire >= 0.3.44, because `PW_KEY_TARGET_OBJECT` was [introduced with that version](https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/9935f921c512f1b3eec9f1608e86d13560ffa27c) – or at least pipewire >= 0.3.47 to cover RHEL 9?

> About the `_XOPEN_SOURCE`: It is defined in `/usr/include/features.h` on Ubuntu 22.04 if the user defines `_GNU_SOURCE`. And `_GNU_SOURCE` was mentioned in this PR shortly [baresip/re#674](https://github.com/baresip/re/pull/674).

On RHEL 9 it builds fine without `_XOPEN_SOURCE` set (glibc 2.34), fails however on Fedora 36 (glibc 2.35). But as you mentioned Ubuntu 22.04 builds fine without (but also glibc 2.35 according to Repology)…maybe @fweimer-rh can help here?

**Comment by robert-scheck** [comment]
> Is this still the relevant build failure? Do you have a link to the SRPM/build log?

Yes and yes:

- F39: https://koji.fedoraproject.org/koji/taskinfo?taskID=98081396 (fails)
- F38: https://koji.fedoraproject.org/koji/taskinfo?taskID=98074826 (fails)
- F37: https://koji.fedoraproject.org/koji/taskinfo?taskID=98074865 (fails)
- F36: https://koji.fedoraproject.org/koji/taskinfo?taskID=98074872 (fails)
- EL9: https://koji.fedoraproject.org/koji/taskinfo?taskID=98074873 (worked)

I'm not sure why the builds fail without `_XOPEN_SOURCE` on Fedora – and whether the proper solution would finally be in baresip upstream or in the `*.spec`. Thank you :)

**Comment by cspiel1** [comment]
> I see. Well, any chance for pipewire >= 0.3.44, because `PW_KEY_TARGET_OBJECT` was [introduced with that version](https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/9935f921c512f1b3eec9f1608e86d13560ffa27c) – or at least pipewire >= 0.3.47 to cover RHEL 9?

In the next days I'll test with pipewire 0.3.47 and then add a version check to cmake.

**Comment by robert-scheck** [comment]
Today I received the notice about a baresip crash while using pipewire 0.3.66 on Fedora 37; `systemd-coredump` delivered:

```
Stack trace of thread 72492:
#0  0x00007f4781aa063b pw_proxy_add_object_listener (libpipewire-0.3.so.0 + 0x7963b)
#1  0x00007f478104ba7d core_method_marshal_add_listener (libpipewire-module-protocol-native.so + 0x17a7d)
#2  0x00007f4781aa8b5f pw_stream_new (libpipewire-0.3.so.0 + 0x81b5f)
#3  0x00007f478426f0b9 pw_playback_alloc (pipewire.so + 0x90b9)
#4  0x00007f47846f0ac6 audio_start (libbaresip.so.4 + 0x19ac6)
#5  0x00007f47846f41a8 update_media (libbaresip.so.4 + 0x1d1a8)
#6  0x00007f47846aa597 invite_resp_handler (libre.so.14 + 0x75597)
#7  0x00007f478469bb3c response_handler.lto_priv.0 (libre.so.14 + 0x66b3c)
#8  0x00007f478469f740 sip_recv.lto_priv.0 (libre.so.14 + 0x6a740)
#9  0x00007f47846a063c udp_recv_handler (libre.so.14 + 0x6b63c)
#10 0x00007f478468d38e udp_read (libre.so.14 + 0x5838e)
#11 0x00007f478466e8fd fd_poll (libre.so.14 + 0x398fd)
#12 0x00007f478466ebf1 re_main (libre.so.14 + 0x39bf1)
#13 0x0000557973150a4a main (baresip + 0x2a4a)
#14 0x00007f478447f510 __libc_start_call_main (libc.so.6 + 0x27510)
#15 0x00007f478447f5c9 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x275c9)
#16 0x0000557973150bf5 _start (baresip + 0x2bf5)

Stack trace of thread 72497:
#0  0x00007f4784564196 epoll_wait (libc.so.6 + 0x10c196)
#1  0x00007f478425aba8 impl_pollfd_wait (libspa-support.so + 0x16ba8)
#2  0x00007f478424b07b loop_iterate (libspa-support.so + 0x707b)
#3  0x00007f4781aadc02 do_loop (libpipewire-0.3.so.0 + 0x86c02)
#4  0x00007f47844e312d start_thread (libc.so.6 + 0x8b12d)
#5  0x00007f4784564bc0 __clone3 (libc.so.6 + 0x10cbc0)
```

The issue occurred after the call was put on hold by the remote side (most likely when the remote side tried to pick it up again).

**Comment by cspiel1** [comment]
Thanks, I'll fix this.

But first: Today I had your build failure https://github.com/baresip/baresip/pull/2439#pullrequestreview-1314596914 on a different devel host with Ubuntu 22.04 (office in Salzburg). In the home office it still builds without any warning. There must be a simple solution.

**Comment by cspiel1** [comment]
@robert-scheck I am no table to reproduce this. Call on-hold and resume works normally.

Instead when starting baresip with `valgrind` I get this when an outgoing call is answered by the remote:
```
==1911218== Thread 7:
==1911218== Jump to the invalid address stated on the next line
==1911218==    at 0x0: ???
==1911218==    by 0x7A65C45: call_process (stream.c:444)
==1911218==    by 0x7A65C45: impl_node_process_output (stream.c:1100)
==1911218==    by 0xB86D49F: impl_node_process (audioadapter.c:1525)
==1911218==    by 0x7A40B58: process_node (impl-node.c:1141)
==1911218==    by 0x7A3FAC6: node_on_fd_events (impl-node.c:1206)
==1911218==    by 0x7ACA36D: loop_iterate (loop.c:452)
==1911218==    by 0x7A1A023: do_loop (data-loop.c:81)
==1911218==    by 0x4A38B42: start_thread (pthread_create.c:442)
==1911218==    by 0x4AC9BB3: clone (clone.S:100)
==1911218==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
```

**Comment by cspiel1** [comment]
- the crash with valgrind is fixed now
- @robert-scheck most likely your crash is also fixed

**Comment by cspiel1** [comment]
I rebased without changes.

@robert-scheck does your setup work now with pipewire?

From my side this is ready for the merge.

**Comment by robert-scheck** [comment]
> @robert-scheck does your setup work now with pipewire?

The tester didn't have the chance (so far) to be in the same situation again. The rest however seems to work properly.

**Comment by sibyakin** [comment]
As early adopter and big fan of Pipewire I do not support Pulseaudio deprecation and deletion. Pipewire has Pulse compatibility layer that is not going anywhere soon. So baresip can use it via pulse module just fine. But older and stable systems that do not have PW can't benefit from new baresip releases. If it's really required to delete something I propose Jack. Pipewire can do everything Jack can but Jack itself is way less common than other two.
btw alsa is not meant to be used directly by user space software that's why PA and PW exist in the first place

**Comment by cspiel1** [comment]
Okay, we will not mark the pulse modul as deprecated. The user may decide which one to use. For the next month and years we maybe could collect experiential reports and comparison of latency and stability between:
- module pulse connected to pulseaudio
- module pulse connected to pipewire
- module pipewire connected directly to pipewire

@alfredh if you agree we could merge this now. It can be activated via configuration. It is only compiled on systems where the pipewire headers are available.

**Comment by pfactum** [comment]
Strange observation: if I switch to `pipewire` while using `stdio.so`, there's no echo of what I type in the terminal any more, although the commands I enter "in blind" still work. If I switch back to `pulse`, I can see what I type in the terminal again.

**Comment by cspiel1** [comment]
How do you switch to `pipewire`?

**Comment by pfactum** [comment]
I've applied this PR to v3.0.0, compiled it, and then in `~/.baresip.config` I have the following:

```
audio_player            pipewire,default
audio_source            pipewire,default
audio_alert             pipewire,default
module                  pipewire.so
```

**Comment by cspiel1** [comment]
Indeed. But more concretely it is when `pipewire` module is loaded the echo  seems to be switched off or at least the typed characters are not directly flushed to stdout. So as soon as there is such a line in the config:
```
module    pipewire.so
```

**Comment by cspiel1** [comment]
I found the reason for the missing echo in the pipewire code:
`./spa/plugins/support/logger.c:378:	setlinebuf(this->file);`

where `file` is `stderr`.

**Comment by cspiel1** [comment]
@pfactum The echo problem is solved now.

**Comment by cspiel1** [comment]
I reported this to `pipewire` developers: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3164

**Comment by robert-scheck** [comment]
So…what's needed to get this merged? I'm keen on this for Fedora and CentOS/RHEL/Rocky Linux 9…

**Comment by cspiel1** [comment]
From my side it is ready for the merge. @alfredh do you still prefer to move this to baresip-apps?

**Comment by alfredh** [comment]
please go ahead and merge it

**Comment by sreimers** [comment]
Currently we are in feature freeze. Please after v3.1.0 release.

**Pull request merged**
