### PR TITLE
webrtc_aecm: added -Wno-missing-field-initializers compile option

### PR DESCRIPTION
**Pull request by juha-h**

### CODE REVIEW

**Comment by alfredh** [comment]
I am not sure if this is needed.

With C99 you can init one struct member by name, and the rest of the members should be zero.

Please post the warning and the compiler details.

**Comment by juha-h** [comment]
Below.  The warning started to appear when I upgrade NDK.  Also, see `modules/webrtc_aec/aec.cpp`.  Since it is there, why not in  `modules/webrtc_aecm/aec.cpp`?
```
/usr/src/libbaresip-android/baresip/modules/webrtc_aecm/aec.cpp:132:37: warning: missing field 'le' initializer [-Wmissing-field-initializers]
  132 |                                    .dech    = webrtc_aecm_decode};
      |                                                                 ^
```

**Comment by juha-h** [comment]
Got the same warning about .enabled field:
```
/usr/src/libbaresip-android/baresip/modules/webrtc_aecm/aec.cpp:135:1: warning: missing field 'enabled' initializer [-Wmissing-field-initializers]
  135 | };
      | ^
```

**Comment by juha-h** [comment]
These warnings appeared with clang version 18.0.3.

**Comment by juha-h** [comment]
If "the rest of the members should be zero", should `.enabled` be intialized to false for backwards compatibility?

**Comment by juha-h** [comment]
Could it be that the warnings only appear with cpp source code?

**Comment by alfredh** [comment]
https://reviews.llvm.org/D157879

**Comment by alfredh** [comment]
I guess there is a difference between C and CPP.

That warning is disabled for the other module:

```
$ git grep missing-field
modules/gzrtp/CMakeLists.txt:    -Wno-missing-field-initializers
modules/webrtc_aec/CMakeLists.txt:  -Wno-missing-field-initializers
```


https://github.com/baresip/baresip/blob/main/modules/webrtc_aec/CMakeLists.txt#L27

**Comment by juha-h** [comment]
OK, but would it be better to avoid the warnings in the code rather than disable them?

**Comment by alfredh** [comment]
It should be almost the same if we update the makefile or the code.

But I am slightly in favour of updating the makefile, since that is done for the other modules.

**Comment by juha-h** [comment]
OK, I can modify CMakeLists.txt instead and remove .le init from webrtc_aec module so that it is compatible with webrtc_aecm module.

**Pull request merged**
