### PR TITLE
ua: add a generic filter API for calls

### PR DESCRIPTION
**Pull request by cspiel1**

### CODE REVIEW

**Comment by juha-h** [comment]
This looks good to me.  OK to merge?

**Comment by cspiel1** [comment]
> Can we get rid of his one? ``` struct call *uag_find_call_state(enum call_state st); ```

Yes, in the next PR. Ok?

**Comment by juha-h** [comment]
Christian Spielberger writes:

> > Can we get rid of his one? ``` struct call *uag_find_call_state(enum call_state st); ```
> 
> Yes, in the next PR. Ok?

OK.

**Comment by cspiel1** [comment]
Thanks for review and merge! I will remove uag_find_call_state() after #1273.

**Comment by juha-h** [comment]
> > Can we get rid of his one? `struct call *uag_find_call_state(enum call_state st);`
> 
> Yes, in the next PR. Ok?

@cspiel1 Could you now remove `uag_find_call_state()` from API?

**Pull request merged**
