### PR TITLE
cmake: add RE_LIBS config and add atomic check

### LINKED ISSUE #2833: Compilation issue, latest code
I used the latest code to compile it in RPI. Before that, it was good,Before that, such as label v3.7
/usr/bin/ld: libbaresip.so.11.7.0: undefined reference to `__atomic_load_8'
/usr/bin/ld: libbaresip.so.11.7.0: undefined reference to `__atomic_store_8'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/baresip_exe.dir/build.make:108: baresip] Error 1
make[1]: *** [CMakeFiles/Makefile2:1188: CMakeFiles/baresip_exe.dir/all] Error 2
make: *** [Makefile:171: all] Error 2

### PR DESCRIPTION
**Pull request by sreimers**
Fixes #2833

### CODE REVIEW

**Comment by alfredh** [comment]
Should we merge this now for the 3.8.0 release, or wait until after the release ?

**Comment by sreimers** [comment]
I think we should merge before release, I currently wait for feedback if this fixes arm gcc builds.

**Comment by jobo-zt** [comment]
Latest testing feedback. #2833

**Comment by jobo-zt** [comment]
Fixed, tested OK.

**Pull request merged**
