### PR TITLE
ua: select proper af and laddr for outgoing IP calls

### PR DESCRIPTION
**Pull request by cspiel1**
- For registrar-less accounts: If the dial URI of an outgoing call is an IP address, we want to select a local address with route to the destination. Note: Nothing changes for cases where the dial URI is a domain name.
- For registrar accounts: Use laddr of registration for SDP.

### CODE REVIEW

**Comment by juha-h** [comment]
Regarding registrar-less accounts, where outbound proxy has been defined with IP address, it should be possible to select local address with route to outbound proxy IP address even when dial URI hostpart is domain name.

**Comment by cspiel1** [comment]
> Regarding registrar-less accounts, where (edit _single_) outbound proxy has been defined with IP address, it should be possible to select local address with route to outbound proxy IP address even when dial URI hostpart is domain name.

Okay. Will check this.

> 
> Edit: Regarding registrar accounts, registration tells to registrar, where the UA can be reached. I don't think registration has anything to do with outbound calls.

But the local IP of the registration most likely will be an IP address which is reachable also for the RTP stream. It makes sense that the RTP stream uses the same interface like the SIP registration.

> 
> Summary: everything should work in case where each UA has a single outbound proxy URI with IP address.

Okay.

**Comment by juha-h** [comment]
I tested outbound calls in the case where accounts have single outbound proxy defined using IP address and correct IP address was used in SDP.

**Comment by juha-h** [comment]
Thanks for the feature.  Is there still more to come, i.e., selecting af and laddr when destination (R-URI or outbound URI host) is domain name?   Just asking if it makes sense to publish new version of my Android app now or wait for the domain name support.

**Comment by cspiel1** [comment]
Domains as dial URI is not so simple. This would mean some API changes and refactoring.
Reason: The DNS request is done at very low level in `re/src/sip/request.c`. And the `laddr` has to be selected in `src/ua.c`.

But I have still some patches for IPv6 link local. I hope that tomorrow there is some time to make a PR.

**Comment by juha-h** [comment]
Christian Spielberger writes:

> Domains as dial URI is not so simple. This would mean some API changes
> and refactoring.
> Reason: The DNS request is done at very low level in
> `re/src/sip/request.c`. And the `laddr` has to be selected in
> `src/ua.c`.

Understand.  Hope there is some way to work it out, because support for
multiple simultaneous networks has been a major issue for a long time.

**Pull request merged**
