### PR TITLE
ua: use sdp connection data instead origin

### PR DESCRIPTION
**Pull request by sreimers**
WebRTC based clients use always `IP4 127.0.0.1` or `IP4 0.0.0.0` as origin `<addrtype> <unicast-address>` for privacy reasons.

https://www.rfc-editor.org/rfc/rfc4566.html#section-5.2

```
 For privacy reasons, it is sometimes desirable to obfuscate the
   username and IP address of the session originator.  If this is a
   concern, an arbitrary <username> and private <unicast-address> MAY be
   chosen to populate the "o=" field, provided that these are selected
   in a manner that does not affect the global uniqueness of the field.
```

### CODE REVIEW

**Comment by sreimers** [comment]
I wonder if sdp origin address is reliable at all?

**Comment by alfredh** [comment]
it is probably better to use the SDP Connection field instead.

A valid SDP must have one or more connection fields, either one in the session level,
or one in the media levels.

**Comment by sreimers** [comment]
@cspiel1 can you check if [sdp connection-address](https://www.rfc-editor.org/rfc/rfc4566.html#section-5.7) works for you? it looks like its used only for preferred address family detection and should more reliable than origin.

WebRTC based clients use always ` IP4 127.0.0.1` or `IP4 0.0.0.0` and as origin `<addrtype> <unicast-address>` for privacy reasons.

**Comment by cspiel1** [comment]
Okay, I will test it. I also think that this is an improvement.

**Comment by cspiel1** [comment]
I tested with:
- IPv4
- IPv6
- IPv6 link local

- The logging `ua: using connection-address ... of SDP offer` was printed like expected.
- Audio+Video works in both directions.

**Comment by sreimers** [comment]
Thanks

**Pull request merged**
