### PR TITLE
Add both Threads and ZLIB to find_package

### PR DESCRIPTION
**Pull request by widgetii**
This fixes Threads package links on my system (cross-compiler arm-linux-musleabi):

```
CMake Error at CMakeLists.txt:196 (target_link_libraries):
  Target "baresip" links to:

    Threads::Threads

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

Because currently it uses `Threads::Threads` in `target_link_libraries` but it never found in `find_package`.
The same idea is for ZLIB, because it seems that clear to use the same way

### CODE REVIEW

**Comment by widgetii** [comment]
I found it failed on Windows, doesn't it support libz, or it's an optional dependency?

**Comment by sreimers** [comment]
Is your re main up to date? `find_package(Threads REQUIRED)` is imported from `re-config.cmake` now.

**Comment by widgetii** [comment]
> Is your re main up to date? `find_package(Threads REQUIRED)` is imported from `re-config.cmake` now.

Just updated, didn't find `re-config.cmake` in the repo

**Comment by sreimers** [comment]
See: https://github.com/baresip/baresip/pull/2089

**Comment by widgetii** [comment]
Got it, you're using upper directory with re as dependency
`find_package(re CONFIG REQUIRED HINTS ../re/cmake)`

but it seems is not a good idea to hardcode paths used on target machine. Moreover, it breaks flexible build systems like Buildroot because it builds `re`, `rem` and `baresip` components as dependency graph and there is no good way to layout them all together

**Comment by sreimers** [comment]
Its only a hint path, if installed it follows the cmake [Config Mode Search Procedure](https://cmake.org/cmake/help/latest/command/find_package.html?highlight=find_package#id7)

**Pull request closed without merging**
