### PR TITLE
sndfile: module_event from main thread

### PR DESCRIPTION
**Pull request by cspiel1**
fixes: https://github.com/baresip/baresip/issues/3135

The main thread allocates and sets the filename and emits the
module event.

### CODE REVIEW

**Comment by cspiel1** [comment]
Need to test, then will set it to Ready.

**Comment by cspiel1** [comment]
Works correct now.
@juha-h please could you test this in your Android App?

**Comment by juha-h** [comment]
Christian Spielberger writes:

> Works correct now.
> @juha-h please could you test this in your Android App?

Works fine if I don't leave/re-enter re_thread when forwarding module
event `dump`.

Is there a way to lock the re thread so that when I leave the re-thread
while forwarding the event, all other re-thread related actions are
queued until I re-enter the thread?

I re-tested and if I use this sndfile.c

https://github.com/baresip/baresip/blob/023ada990de350fab0d0a3599fead92b56208ef4/modules/sndfile/sndfile.c 

everything works fine even when I leave/re-enter re_thread while
forwarding module event `dump`.  How can this be explained?

**Comment by alfredh** [comment]
this fix looks good.

There should be no need to change any application code.

**Pull request merged**
