### PR TITLE
debug_cmd: fix gcc warning implicit conversion to enum ua_event

### PR DESCRIPTION
**Pull request by cspiel1**

### CODE REVIEW

**Comment by alfredh** [comment]
the patch itself is fine as it is.

I would rather suggest to extend the type `enum ua_event` instead with your new event:

```c
/** Events from User-Agent */
enum ua_event {
	UA_EVENT_REGISTERING = 0,
	UA_EVENT_REGISTER_OK,
	UA_EVENT_REGISTER_FAIL,
	UA_EVENT_UNREGISTERING,
	UA_EVENT_FALLBACK_OK,
	UA_EVENT_FALLBACK_FAIL,
	UA_EVENT_MWI_NOTIFY,
	UA_EVENT_SHUTDOWN,
	UA_EVENT_EXIT,

	UA_EVENT_CALL_INCOMING,
	UA_EVENT_CALL_RINGING,
	UA_EVENT_CALL_PROGRESS,
	UA_EVENT_CALL_ESTABLISHED,
	UA_EVENT_CALL_CLOSED,
	UA_EVENT_CALL_TRANSFER,
	UA_EVENT_CALL_TRANSFER_FAILED,
	UA_EVENT_CALL_DTMF_START,
	UA_EVENT_CALL_DTMF_END,
	UA_EVENT_CALL_RTPESTAB,
	UA_EVENT_CALL_RTCP,
	UA_EVENT_CALL_MENC,
	UA_EVENT_VU_TX,
	UA_EVENT_VU_RX,
	UA_EVENT_AUDIO_ERROR,
	UA_EVENT_CALL_LOCAL_SDP,      /**< param: offer or answer */
	UA_EVENT_CALL_REMOTE_SDP,     /**< param: offer or answer */

	UA_EVENT_MAX,
};
```

(add your new type before MAX).

With this approach, no casting is needed :)

**Comment by cspiel1** [comment]
Ok. But we will add more events sent from modules in future PRs. I suggest to add a general event type that can be used by any module
```
UA_EVENT_GENERAL
```
or
```
UA_EVENT_OTHER
```
Matching in the application can be done with the event text.

**Comment by alfredh** [comment]
yes, good idea to add a generic type. suggestions:

- Echo
- Print
- Custom

**Comment by juha-h** [comment]
Makes sense to me too., since I have had to patch baresip in order to support a new event:
```
@@ -745,6 +745,8 @@ enum ua_event {
 	UA_EVENT_CALL_LOCAL_SDP,      /**< param: offer or answer */
 	UA_EVENT_CALL_REMOTE_SDP,     /**< param: offer or answer */
 
+	UA_EVENT_GET_PASSWORD,
+
 	UA_EVENT_MAX,
 };
```

**Comment by cspiel1** [comment]
Ok, custom sounds good:
```
UA_EVENT_CUSTOM
```

**Pull request merged**
