### PR TITLE
pipewire: lock loop while starting and registry scan

### PR DESCRIPTION
**Pull request by cspiel1**
Fixes: https://github.com/baresip/baresip/issues/3064

### CODE REVIEW

**Comment by cspiel1** [comment]
@HectorGarciaMiguel please could you test this solution with pipewire >= 0.3.68?

**Comment by HectorGarciaMiguel** [comment]
> @HectorGarciaMiguel please could you test this solution with pipewire >= 0.3.68?
> 
> Is there still a "check thread and locking: Operation not permitted"?

Ok I'll try, let me have a few minutes

**Comment by HectorGarciaMiguel** [comment]
> @HectorGarciaMiguel please could you test this solution with pipewire >= 0.3.68?
> 
> Is there still a "check thread and locking: Operation not permitted"?

Ok, I have also tested with the 1.2.0 pipewire version, the last one, and the message is no longer displayed.

**Comment by cspiel1** [comment]
Thanks! Any further suggestions? Should we merge this?

**Pull request merged**
