### PR TITLE
ua,uag: split ua.c and uag.c

### PR DESCRIPTION
**Pull request by cspiel1**
- uag.c contains code for User-Agent Group. E.g. functions that operate on the
  list of User-Agents.
- ua.c contains code for User-Agent. E.g. functions that operate on one User-
  Agent.

### CODE REVIEW

**Comment by cspiel1** [comment]
This can also wait be put to v1.2.0.

**Comment by alfredh** [comment]
can you please resolve the conflicts and rebase ?

**Comment by cspiel1** [comment]
Maybe this should be merged last. Will rebase it now. And have to do this again.

**Comment by alfredh** [comment]
is it ready to merge now ?

**Comment by cspiel1** [comment]
Again rebased. Carefully checked the `git log -p src/ua.c`.

**Comment by alfredh** [comment]
thanks a lot for doing this work :)

**Pull request merged**
