### PR TITLE
Menu fixes for play tones2

### PR DESCRIPTION
**Pull request by cspiel1**
Replaces #1273.
- ringback tone was not played
- fixes when and what to play for incoming calls
- resume right tone if a call terminates
- remove ANSI bell alert

### CODE REVIEW

**Comment by cspiel1** [comment]
@sreimers This travis error is new. 
```
Err:34 https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04  Release
37
  Certificate verification failed: The certificate is NOT trusted. The received OCSP status response is invalid.  Could not handshake: Error in the certificate verification. [IP: 195.135.221.134 443]
```

**Comment by juha-h** [comment]
This PR looks good to me, but I don't know about the ubuntu check errors.

**Comment by cspiel1** [comment]
Thanks for review! It's green now. Magic!

@alfredh Do you want to have a look on it? It also removes the ANSI bell alert in menu.

**Comment by cspiel1** [comment]
@juha-h Should we merge this now? The ringback tone is not working currently.

**Comment by juha-h** [comment]
OK, let's do the merge.

**Pull request merged**
