### PR TITLE
cmake: add only non-system link paths to rpath (fixes #2849)

### LINKED ISSUE #2849: Non-conditional and wrong standard RPATHs break building on Fedora
Unfortunately, commits d46df528bdaf284b76da1ae904af3d74682b497f and 38f782391f203cbc3baa9f8c8ffde24a1608c8f7 (related to #2831, #2837 and #2839) break building baresip on Fedora, because it introduces non-conditional and wrong standard RPATHs:

Practically, RPATH should only be set if the library path does not match the default library path. In this case, a (64 bit) ELF binary in `/usr/bin` or `/usr/lib64` even as a RPATH to (32 bit) `/usr/lib`:

```
ERROR   0001: file '/usr/lib64/libbaresip.so.12.8.0' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/x11.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/stun.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/evdev.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/account.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/stdio.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/turn.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/aubridge.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/uuid.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/bin/baresip' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/auconv.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/vidbridge.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/aufile.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/vidinfo.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/auresamp.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/vumeter.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/ausine.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/aac.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/cons.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/alsa.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/contact.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/av1.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/ctrl_tcp.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/codec2.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/debug_cmd.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/ctrl_dbus.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/ebuacip.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/gst.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/echo.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/gtk.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/fakevideo.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/dtls_srtp.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/g711.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/jack.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/httpd.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/mpa.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/httpreq.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/mqtt.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/ice.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/opus.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/l16.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/opus_multistream.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/menu.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/snapshot.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/mixausrc.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/portaudio.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/mixminus.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/pulse.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/multicast.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/pipewire.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/mwi.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/sdl.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/natpmp.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/sndfile.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/netroam.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/syslog.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/pcp.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/presence.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/g722.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/g726.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/rtcpsummary.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/plc.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/selfview.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/serreg.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/v4l2.so' contains a standard runpath '/usr/lib' in [/usr/lib]
ERROR   0001: file '/usr/lib64/baresip/modules/vp8.so' contains a standard runpath '/usr/lib' in [/usr/lib]
```

### PR DESCRIPTION
**Pull request by robert-scheck**
This patch, even while maybe imperfect from CMake perspective, ensures that only non-system directories used for linking are added to RPATH. Fedora's `/usr/lib/rpm/check-rpaths` claims unnecessary standard RPATHs (e.g. `/usr/lib`).

While such RPATHs might be treated as a minor issue, they are still introducing redundant searchpaths without providing a benefit. They can also cause errors in multilib environments (e.g. `/usr/lib` instead of `/usr/lib64`on 64 bit Fedora systems).

### CODE REVIEW

**Comment by robert-scheck** [comment]
@bacterik, do you see any chance to test pull request this on macOS?

**Comment by sreimers** [comment]
Maybe we should set rpath only on macOS and iOS? 

```cmake
if(APPLE)
```

**Comment by robert-scheck** [comment]
> Maybe we should set rpath only on macOS and iOS?

Personally, I wouldn't do this, because Linux users might want to install baresip on non-default paths for whatever reasons.

**Comment by alfredh** [comment]
tested OK on macOS 12.7:

```
Alfreds-MBP-M1:baresip alfredh$ patch -p1 < 2850.diff 
patching file CMakeLists.txt
Alfreds-MBP-M1:baresip alfredh$ cmake .
-- The C compiler identification is AppleClang 14.0.0.14000029
-- The CXX compiler identification is AppleClang 14.0.0.14000029
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found RE: /usr/local/lib/libre.dylib  
-- Looking for backtrace
-- Looking for backtrace - found
-- backtrace facility detected in default set of libraries
-- Found Backtrace: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include  
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found ZLIB: /opt/local/lib/libz.dylib (found version "1.3.#define ZLIB_VERSION "1.3"") 
-- Found OpenSSL: /opt/local/libexec/openssl3/lib/libcrypto.dylib (found suitable version "3.2.0", minimum required is "1.1.1")  
-- Setting build type to 'Debug' as none was specified.
-- Looking for arc4random
-- Looking for arc4random - found
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Looking for getopt.h
-- Looking for getopt.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for res_ninit
-- Looking for res_ninit - found
-- Looking for thrd_create
-- Looking for thrd_create - not found
-- Looking for threads.h
-- Looking for threads.h - not found
-- Looking for accept4
-- Looking for accept4 - not found
-- Looking for epoll_create
-- Looking for epoll_create - not found
-- Looking for kqueue
-- Looking for kqueue - found
-- Looking for sys/prctl.h
-- Looking for sys/prctl.h - not found
-- Performing Test atomic_test
-- Performing Test atomic_test - Success
-- Checking for one of the modules 'fdk-aac'
-- Could NOT find AAC (missing: AAC_LIBRARY AAC_INCLUDE_DIR) 
-- Could NOT find ALSA (missing: ALSA_LIBRARY ALSA_INCLUDE_DIR) 
-- Found AMR: TRUE  
-- Found PkgConfig: /opt/local/bin/pkg-config (found version "0.29.2") 
-- Checking for one of the modules 'aptx'
-- Could NOT find APTX (missing: APTX_LIBRARY APTX_INCLUDE_DIR) 
-- Found AOM: /opt/local/lib/libaom.dylib (found version "3.8.0") 
-- Checking for one of the modules 'codec2'
-- Could NOT find CODEC2 (missing: CODEC2_LIBRARY CODEC2_INCLUDE_DIR) 
-- Could NOT find DIRECTFB (missing: DIRECTFB_LIBRARIES DIRECTFB_INCLUDE_DIR) 
-- Found FFMPEG: /opt/homebrew/bin/../lib/libavcodec.dylib (found version "#define LIBAVCODEC_VERSION_MINOR  31;#define LIBAVCODEC_VERSION_MICRO 102.31.102") found components: avcodec avfilter avformat swscale swresample avdevice avutil 
-- Checking for one of the modules 'g7221'
-- Could NOT find G7221 (missing: G7221_LIBRARY G7221_INCLUDE_DIR) 
-- Checking for module 'gio-unix-2.0'
--   Found gio-unix-2.0, version 2.78.0
-- Found GIO: /opt/local/lib/libglib-2.0.dylib  
-- Could NOT find GST (missing: GST_FOUND) 
-- Checking for module 'gtk+-3.0'
--   No package 'gtk+-3.0' found
-- Could NOT find GTK3 (missing: GTK3_LIBRARIES GTK3_CFLAGS GTK3_CFLAGS_OTHER) 
-- Could NOT find GZRTP (missing: GZRTP_LIBRARY GZRTP_INCLUDE_DIR) 
-- Checking for one of the modules 'jack'
-- Could NOT find JACK (missing: JACK_LIBRARY JACK_INCLUDE_DIR) 
-- Could NOT find MOSQUITTO (missing: MOSQUITTO_LIBRARY MOSQUITTO_INCLUDE_DIR) 
-- libmosquitto include dir: MOSQUITTO_INCLUDE_DIR-NOTFOUND
-- libmosquitto: MOSQUITTO_LIBRARY-NOTFOUND
-- Checking for one of the modules 'twolame'
-- Checking for one of the modules 'mpg123'
-- Checking for one of the modules 'speexdsp'
-- Could NOT find MPA (missing: MPA_LIBRARIES MPA_INCLUDE_DIRS) 
-- Could NOT find OPENSLES (missing: OPENSLES_LIBRARY OPENSLES_INCLUDE_DIR) 
-- Checking for one of the modules 'opus'
-- Found OPUS: /opt/local/lib/libopus.dylib  
-- Found PNG: /opt/local/lib/libpng.dylib  
-- Checking for one of the modules 'portaudio'
-- Found PORTAUDIO: /opt/homebrew/lib/libportaudio.dylib  
-- Checking for one of the modules 'pulse'
-- Could NOT find PULSE (missing: PULSE_LIBRARY PULSE_INCLUDE_DIR) 
-- Checking for one of the modules 'libpipewire-0.3'
-- Could NOT find PIPEWIRE (missing: PIPEWIRE_INCLUDE_DIRS PIPEWIRE_LIBRARIES) 
-- Checking for one of the modules 'sdl2'
-- Found SDL: /opt/local/lib/libSDL2.dylib  
-- Checking for module 'sndfile'
--   No package 'sndfile' found
-- Found SNDFILE: /opt/homebrew/include  
-- Found SPANDSP: /opt/homebrew/lib/libspandsp.dylib  
-- Checking for module 'libv4l2'
--   No package 'libv4l2' found
-- Could NOT find V4L2 (missing: V4L2_LIBRARY V4L2_INCLUDE_DIR) 
-- Found VPX: /opt/local/lib/libvpx.dylib  
-- Could NOT find WEBRTC_AEC (missing: WEBRTC_AEC_LIBRARY WEBRTC_AEC_INCLUDE_DIR) 
-- Could NOT find WEBRTC_AECM (missing: WEBRTC_AECM_LIBRARY WEBRTC_AECM_INCLUDE_DIR) 
-- Found X11: /opt/local/include   
-- Looking for XOpenDisplay in /opt/local/lib/libX11.dylib;/opt/local/lib/libXext.dylib
-- Looking for XOpenDisplay in /opt/local/lib/libX11.dylib;/opt/local/lib/libXext.dylib - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/alfredh/tmp/baresip
Alfreds-MBP-M1:baresip alfredh$ make
[  0%] Building C object CMakeFiles/baresip.dir/src/account.c.o
[  0%] Building C object CMakeFiles/baresip.dir/src/aucodec.c.o
[  1%] Building C object CMakeFiles/baresip.dir/src/audio.c.o
[  1%] Building C object CMakeFiles/baresip.dir/src/aufilt.c.o
[  1%] Building C object CMakeFiles/baresip.dir/src/auplay.c.o
[  2%] Building C object CMakeFiles/baresip.dir/src/aureceiver.c.o
[  2%] Building C object CMakeFiles/baresip.dir/src/ausrc.c.o
...
```

**Comment by robert-scheck** [comment]
> tested OK on macOS 12.7:

Given you only showed build-time output…the (breaking) CMake code was added for a reported run-time issue on macOS.

**Comment by larsimmisch** [comment]
@robert-scheck Looks good to me.

I tested this on MacOS 14.2.1 by running:
- `cmake -B build`
- `cmake --build build`
- `cmake --install build`

And then running `baresip` from the path. `baresip` started up fine.

**Pull request merged**
