### PR TITLE
ci: migrate from make to CMake

### PR DESCRIPTION
**Pull request by alfredh**

### CODE REVIEW

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/baresip/baresip/pull/2127
> 
> -- Commit Summary --
> 
>   * test: remove Makefile
> 
> -- File Changes --
> 
>     D Makefile (436)

Does this mean that the Makefile at the root of baresip is deleted?  If
so, Would it be possible to keep the main Makefile at least for some time
parallel to cmake make process?

**Comment by alfredh** [comment]
> Alfred E. Heggestad writes:
> You can view, comment on, or merge this pull request online at: #2127 -- Commit Summary -- * test: remove Makefile -- File Changes -- D Makefile (436)
> Does this mean that the Makefile at the root of baresip is deleted? If so, Would it be possible to keep the main Makefile at least for some time parallel to cmake make process?

this PR is only a test to provoke the CI with a missing Makefile.

I am not planning to commit this. The root Makefile will not be deleted.

**Comment by juha-h** [comment]
Would Debian package build still work if main Makefile is removed?
debian/rules has:

configure: configure-stamp
configure-stamp:
	dh_testdir
	touch configure-stamp


build: build-stamp

build-stamp: configure-stamp 
	dh_testdir
	$(MAKE) RELEASE=1 $(BARESIP_FLAGS) DESTDIR=$(CURDIR)/debian/baresip \
		EXTRA_CFLAGS=$(EXTRA_CFLAGS) \
		EXTRA_LFLAGS=$(EXTRA_LFLAGS)
	touch build-stamp

**Comment by sreimers** [comment]
> Would Debian package build still work if main Makefile is removed? debian/rules has:

We should migrate this to [CPack DEB generator](https://cmake.org/cmake/help/latest/cpack_gen/deb.html), will try to make a PR.

**Pull request closed without merging**
