### PR TITLE
aufile: joind already terminated thread frees stack

### PR DESCRIPTION
**Pull request by cspiel1**

### CODE REVIEW

**Comment by sreimers** [comment]
One problem, if `thread_create_name()` fails, `thrd_join()` segfaults.

**Comment by sreimers** [comment]
Can you try this:

```diff
diff --git a/modules/aufile/aufile_src.c b/modules/aufile/aufile_src.c
index 07bcca7b..3a836076 100644
--- a/modules/aufile/aufile_src.c
+++ b/modules/aufile/aufile_src.c
@@ -89,7 +89,7 @@ static int src_thread(void *arg)
                ts += st->ptime;
 
                if (aubuf_cur_size(st->aubuf) == 0)
-                       re_atomic_rlx_set(&st->run, false);
+                       break;
        }
 
        mem_deref(sampv);
```

**Comment by cspiel1** [comment]
Pls let me know if I should merge this! I'd like to squash the commits and set an appropriate commit message.

**Comment by sreimers** [comment]
Looks fine, please merge.

**Pull request merged**
