### PR TITLE
Cmake of webrtc_aec module plus remove of unused aec.cpp var

### PR DESCRIPTION
**Pull request by juha-h**

### CODE REVIEW

**Comment by juha-h** [comment]
I don't know why Ubuntu build fails like this:
```
c++: error: unrecognized command-line option ‘-Watomic-implicit-seq-cst’
gmake[2]: *** [modules/webrtc_aec/CMakeFiles/webrtc_aec.dir/build.make:90: modules/webrtc_aec/CMakeFiles/webrtc_aec.dir/decode.cpp.o] Error 1
```
Cmake build of webrtc_acm module works fine on my Debian 11. 

‘-Watomic-implicit-seq-cst’ comes from main CMakeLists.txt:
```
if(CMAKE_C_COMPILER_ID MATCHES "Clang")
  add_compile_options(-Wshorten-64-to-32 -Watomic-implicit-seq-cst)
endif()
```

**Comment by sreimers** [comment]
This should fix the problem: https://github.com/baresip/baresip/pull/2145

**Comment by sreimers** [comment]
Can you try to rebase this PR?

**Comment by juha-h** [comment]
Also -Wshorten-64-to-32 is not recognized:
```
c++: error: unrecognized command-line option ‘-Wshorten-64-to-32’
gmake[2]: *** [modules/webrtc_aec/CMakeFiles/webrtc_aec.dir/build.make:76: modules/webrtc_aec/CMakeFiles/webrtc_aec.dir/aec.cpp.o] Error 1
```

**Comment by juha-h** [comment]
Build works on my Debian 11, because CXX compiler is GNU:
```
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
```
Well, that is not the reason, since build works also when I ask cmake to use clang++:
```
cmake .. -DMODULES="stdio;opus;amr;webrtc_aec;..." -DCMAKE_CXX_COMPILER="clang++"
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is Clang 11.0.1
...
make
...
[ 41%] Building CXX object modules/webrtc_aec/CMakeFiles/webrtc_aec.dir/aec.cpp.o
[ 42%] Building CXX object modules/webrtc_aec/CMakeFiles/webrtc_aec.dir/decode.cpp.o
[ 43%] Building CXX object modules/webrtc_aec/CMakeFiles/webrtc_aec.dir/encode.cpp.o
[ 43%] Linking CXX shared module webrtc_aec.so
```

**Comment by juha-h** [comment]
OK, now after https://github.com/baresip/baresip/pull/2146 all tests succeeded.

**Comment by sreimers** [comment]
Yes the problem in CI is that `clang` is used for `CC` and `CXX` is `gcc`, but something that can happen so nice it works now. But `This branch cannot be rebased due to conflicts` can you resolve the conflict with `main`?

**Comment by juha-h** [comment]
> Yes the problem in CI is that `clang` is used for `CC` and `CXX` is `gcc`, but something that can happen so nice it works now. But `This branch cannot be rebased due to conflicts` can you resolve the conflict with `main`?

I thought that I already resolved the conflicts.  There is now "This branch has no conflicts with the base branch
Merging can be performed automatically. ".

**Pull request merged**
