### PR TITLE
ci: add libwebrtc-audio-processing-dev (module webrtc_aec)

### PR DESCRIPTION
**Pull request by sreimers**

### CODE REVIEW

**Comment by alfredh** [comment]
not sure if webrtc_aec is auto detected

perhaps EXTRA_MODULES=webrtc_aec ?

**Comment by sreimers** [comment]
I just added auto detection. Clang support is broken due to an incompatible C++ compiler option, I'll take a closer look.

**Comment by juha-h** [comment]
On Debian 11, test
```
pkg-config --exists "webrtc-audio-processing >= 0.3.1" && echo "yes"
```
fails, but this would succeed:
```
pkg-config --exists "webrtc-audio-processing >= 0.3" && echo "yes"
```
Is version 0.3.1 mandatory?

**Comment by sreimers** [comment]
> the C++ compiler also has to be set explicitly:
> 
> ```
> $ make CC=clang CXX=clang++
> ```

I was not able to compile with clang++, looks like webrtc has strange strict gcc header dependencies on archlinux. Will recheck on ubuntu.

```
In file included from modules/webrtc_aec/encode.cpp:14:
In file included from modules/webrtc_aec/aec.h:10:
In file included from /usr/include/webrtc_audio_processing/webrtc/modules/audio_processing/include/audio_processing.h:20:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/vector:60:
In file included from /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/bits/stl_algobase.h:63:
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/ext/numeric_traits.h:85:52: error: default initialization of an object of const type 'const char'
    const _Value __numeric_traits_integer<_Value>::__max;
```

**Comment by juha-h** [comment]
Yes, with this kind of `module.mk` webrtc_aec combiles fine on Debian 11:
```
MOD		:= webrtc_aec

$(MOD)_SRCS	+= aec.cpp
$(MOD)_SRCS	+= encode.cpp
$(MOD)_SRCS	+= decode.cpp

CPPFLAGS	+= -isystem /usr/include/webrtc_audio_processing

$(MOD)_LFLAGS	+= \
	-L/usr/lib/x86_64-linux-gnu/ \
	-lstdc++


include mk/mod.mk
```

**Comment by alfredh** [comment]
great work! thanks!

**Comment by alfredh** [comment]
btw: I get this on OSX:

```
  CXX [M] build-x86_64/modules/webrtc_aec/aec.o
In file included from modules/webrtc_aec/aec.cpp:8:
In file included from ../rem/include/rem.h:15:
In file included from ../rem/include/rem_audio.h:10:
../rem/include/rem_aubuf.h:33:9: error: no matching function for call to 'aubuf_append_auframe'
        return aubuf_append_auframe(ab, mb, NULL);
               ^~~~~~~~~~~~~~~~~~~~
../rem/include/rem_aubuf.h:10:6: note: candidate function not viable: cannot convert argument of incomplete type
      'void *' to 'struct auframe *' for 3rd argument
int  aubuf_append_auframe(struct aubuf *ab, struct mbuf *mb,
     ^
In file included from modules/webrtc_aec/aec.cpp:13:
modules/webrtc_aec/aec.h:10:10: fatal error: 'webrtc/modules/audio_processing/include/audio_processing.h' file not
      found
#include <webrtc/modules/audio_processing/include/audio_processing.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
make: *** [build-x86_64/modules/webrtc_aec/aec.o] Error 1
```

I think that C++ is more strict regarding casting than C, perhaps it is related ?

**Pull request merged**
