### PR TITLE
call: start streams in sipsess_estab_handler

### PR DESCRIPTION
**Pull request by maximilianfridrich**
As discussed in #2882.

### CODE REVIEW

**Comment by cspiel1** [comment]
Looks good now. The ACK triggers the `estabh` in listen.c:170, finally the `sipsess_estab_handler()` in baresip. Here we start with streaming the WAV file, if aufile is configured as ausrc. The first audio frames are not lost any more.

Some cleanup should be done in future PRs:
- `update_streams()` vs `call_stream_start()` which do similar tasks
- Check if early-audio works in combination with aufile as ausrc.

**Comment by maximilianfridrich** [comment]
I have tested early-audio, works as before (this PR does not change or break the early-audio feature).

**Comment by joaquinjsb** [comment]
sorry for the late reply,
I have an error building from the pr branch.

did I miss something?

```
     
[ 33%] Building C object modules/syslog/CMakeFiles/syslog.dir/syslog.c.o
1 warning generated.
1 warning generated.
1 warning generated.
1 warning generated.
/Users/joaquin/baresip/fixed/src/call.c:3251:16: error: call to undeclared function 'sipsess_sdp_neg_state'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        return call ? sipsess_sdp_neg_state(call->sess) : SDP_NEG_NONE;
                      ^
/Users/joaquin/baresip/fixed/src/call.c:3251:16: note: did you mean 'call_sdp_neg_state'?
/Users/joaquin/baresip/fixed/src/call.c:3249:20: note: 'call_sdp_neg_state' declared here
enum sdp_neg_state call_sdp_neg_state(const struct call *call)
                   ^
1 warning generated.
In file included from /Users/joaquin/baresip/fixed/modules/presence/presence.c:7:
/Users/joaquin/baresip/fixed/include/baresip.h:269:6: warning: ISO C forbids forward references to 'enum' types [-Wpedantic]
enum sdp_neg_state call_sdp_neg_state(const struct call *call);
     ^
In file included from /Users/joaquin/baresip/fixed/modules/coreaudio/player.c:9:
/Users/joaquin/baresip/fixed/include/baresip.h:269:6: warning: ISO C forbids forward references to 'enum' types [-Wpedantic]
enum sdp_neg_state call_sdp_neg_state(const struct call *call);
     ^
[ 33%] Building C object CMakeFiles/baresip.dir/src/vidisp.c.o
1 warning generated.
1 warning generated.
/Users/joaquin/baresip/fixed/src/call.c:3251:52: error: use of undeclared identifier 'SDP_NEG_NONE'
        return call ? sipsess_sdp_neg_state(call->sess) : SDP_NEG_NONE;
                                                          ^
/Users/joaquin/baresip/fixed/src/call.c:3267:21: error: variable has incomplete type 'enum sdp_neg_state'
        enum sdp_neg_state sdp_state = call_sdp_neg_state(call);
                           ^
/Users/joaquin/baresip/fixed/include/baresip.h:269:6: note: forward declaration of 'enum sdp_neg_state'
enum sdp_neg_state call_sdp_neg_state(const struct call *call);
     ^
[ 34%] Building C object modules/turn/CMakeFiles/turn.dir/turn.c.o`

**Comment by maximilianfridrich** [comment]
Unfortunately, I can not reproduce your described behavior. I ran `./baresip -e "/ausrc aufile,/usr/local/share/baresip/sample.wav"` and then on this BareSIP instance I run `/dial`. Once the callee answers the call, the audio file starts playing from the beginning - no audio is lost. The same happens when the baresip instance is the callee and answers the call.

Could you provide more details about your configs, accounts and which command is run at caller and callee?

**Comment by joaquinjsb** [comment]
this is my config,
https://pastebin.com/raw/tL79wAGu

for the account, here is the string, I'm calling from baresip to an public sip.
<sip:username@server;transport=tcp>;auth_pass=passwd;outbound="sip:username:password@server;transport=tcp";auth_user=username;sipnat=outbound

let me know if you need my .wav, it's just an audio of 20s, if you let the call ring for 15s, and then answer the call, you'll only listen to the last 5s

**Comment by maximilianfridrich** [comment]
Thank you! Still no luck though. Could you run `./baresip -v -s -e "/ausrc aufile,/usr/local/share/baresip/sample.wav"` and post the debug and trace output?

**Comment by joaquinjsb** [comment]
https://pastebin.com/raw/n8sjKq99

**Comment by maximilianfridrich** [comment]
@joaquinjsb The server sends a 183 response without a media direction, which means `sendrecv`. Ttherefore this is an early-media scenario and the file streaming starts as soon as we receive the 183 response from the peer. This is the expected behavior.

**Comment by joaquinjsb** [comment]
> @joaquinjsb The server sends a 183 response without a media direction, which means `sendrecv`. Therefore this is an early-media scenario and the file streaming starts as soon as we receive the 183 response from the peer. This is the expected behavior.

so that's probably a "faulty" server side implementation?

**Comment by maximilianfridrich** [comment]
It's not really faulty, but the server sends a 183 which is usually used to start an "early media" session - i.e. start sending and/or receiving audio/video before the callee has answered the call.

You could check if the server or UA on the other side has an option to disable early media or session progress.

**Comment by joaquinjsb** [comment]
> It's not really faulty, but the server sends a 183 which is usually used to start an "early media" session - i.e. start sending and/or receiving audio/video before the callee has answered the call.
> 
> You could check if the server or UA on the other side has an option to disable early media or session progress.

thanks, I'll try to get a feedback from the provider, so I guess there's no possible workaround for baresip right?

**Comment by maximilianfridrich** [comment]
Unfortunately, not through BareSIP configuration. You'd have to write an application that listens to BareSIP events (e.g. on D-Bus) and then sends the `/play` command once the `UA_EVENT_CALL_ESTABLISHED` is received.

**Comment by joaquinjsb** [comment]
> Unfortunately, not through BareSIP configuration. You'd have to write an application that listens to BareSIP events (e.g. on D-Bus, or an application module) and then sends the `/play` command once the `UA_EVENT_CALL_ESTABLISHED` is received.

not sure if I could handle that via java with the command line launcher, do your mqtt handle that, or the tcp/udp console?

**Comment by maximilianfridrich** [comment]
@joaquinjsb Let's move this discussion to #2882 (away from this PR).

**Comment by cspiel1** [comment]
@alfredh This is ready for merge. See:
- https://github.com/baresip/baresip/issues/2882#issuecomment-1903584746
- https://github.com/baresip/baresip/pull/2909#issuecomment-1931686426

Any further suggestions?

**Pull request merged**
