### PR TITLE
release v2.8.1

### PR DESCRIPTION
**Pull request by cspiel1**
### Create/Prepare PRs for new Release (re/rem/baresip)
- [x] Update `CHANGELOG.md`
  - Click `Draft a new release` on Release page
  - Fill a new release tag version and title (like v2.4.0)
  - Press `Auto-generate Release notes` 
  - **Save as draft** (don't publish yet)
  - Copy release notes to `CHANGELOG.md`
- [x] Update `debian/changelog`
- [x] Check version numbers
  - `CMakefile`
  - `Makefile`
  - `include/baresip.h` (baresip only)
- [x] Check ABI compatibility (only `re` and `rem` for now)
  - `CMakefile` (Bump PROJECT_SOVERSION)
  - `Makefile` (Bump ABI_MAJOR)
- [ ] <s>Comment out PRE Release identifier `-dev`</s>
  - <s>`CMakefile` </s>
  - <s>`Makefile` </s>
- [ ] All tests green? [re/rem/retest/baresip]

### Release
- [ ] Merge PRs in this order
  - libre
  - librem
  - retest (needs only a version tag - no PR)
  - baresip
- [ ] Publish draft Releases (follow the same order)
  - Maybe `Auto-generate Release notes` is needed to update (delete last notes first)

### After Release
- [ ] Merge main branches to stable
  - re - https://github.com/baresip/re/compare/stable...main?expand=1
  - rem - https://github.com/baresip/rem/compare/stable...main?expand=1
  - retest - https://github.com/baresip/retest/compare/stable...main?expand=1
  - baresip - https://github.com/baresip/baresip/compare/stable...main?expand=1
- [ ] Bump main branch versions with PRE Release identifier `-dev`
  - `CMakefile`
  - `Makefile`
  - `include/baresip.h` (baresip only)

### CODE REVIEW

**Comment by sreimers** [comment]
looks like `include/baresip.h` version bump is missing

**Comment by alfredh** [comment]
try this:

```
$ make version
```

**Comment by cspiel1** [comment]
> looks like `include/baresip.h` version bump is missing

Pushed just a moment ago.

```
$ make version
updating version number to 2.8.1
```
Also mention the v2.8.1 in the debian/changelog?

**Comment by sreimers** [comment]
Looks good to me know.

**Comment by cspiel1** [comment]
There is one more thing missing:
```
$ git diff
diff --git a/mk/Doxyfile b/mk/Doxyfile
index 9f25e5b57..9ab137380 100644
--- a/mk/Doxyfile
+++ b/mk/Doxyfile
@@ -4,7 +4,7 @@
 # Project related configuration options
 #---------------------------------------------------------------------------
 PROJECT_NAME           = baresip
-PROJECT_NUMBER         = 2.3.0
+PROJECT_NUMBER         = 2.8.1
 OUTPUT_DIRECTORY       = ../baresip-dox
 CREATE_SUBDIRS         = NO
 OUTPUT_LANGUAGE        = English
```

**Comment by sreimers** [comment]
We should document the `make version`, but I don't think we need a extra release for Doxyfile now.

**Comment by cspiel1** [comment]
Should we:
- Add `version` targets in Makefile of `re`, `rem`?
  - Or we drop Makefile soon.
- Add `VER_PRE` in baresip Makefile?
- Add `PROJECT_VERSION_FULL` with "-dev" version support to `rem` and `baresip` CMakeLists.txt?

**Pull request merged**
