### PR TITLE
Attended Transfer on GTK

### PR DESCRIPTION
**Pull request by mbattista**
I implemented an attended transfer for gtk.

It still has some rough edges, e.g. you have to set the call on hold manually to enable attended transfer, but it is functional (at least it worked on a `starface` telephony system.

Edit: I also fixed a bug with clean number in this merge request, which includes `ctype.h` on the `menu` and `gtk` module. It seems that either a contact formatted entry returns a errorcode from `re_regex` or I missunderstood how the function should be used.

On a sidenote, I could segfault re_regex with `int err = re_regex(str, str_len(str), "[0-9]+");` (I wanted to check "[0-9\\-\\.\\+\\(\\)"]+, but it to showcase the error, this was the shortest regex I tested) and the following string: `"Doe, John" <sip:75@192.0.2.55>`, which is why i now check the string with ctype instead.
Should I make an issue on `baresip/re` for this?

### CODE REVIEW

**Comment by mbattista** [comment]
I could probably make a similar pull request for the menu module if wanted.

**Comment by juha-h** [comment]
mbattista writes:

> I could probably make a similar pull request for the menu module if
> wanted.

Please do.  I have reported problem with the current transfer feature

  https://groups.google.com/g/baresip/c/NUHJeMqAyTw

and attended version would be an improvement.

**Comment by alfredh** [comment]
should we move gtk module to baresip-apps ?

https://github.com/baresip/baresip-apps


since gtk module is the only GUI module, I have a feeling that it does not really belong
in the main baresip repo ...

**Comment by alfredh** [comment]
for `re_regex` each pattern matching must have a corresponding `struct pl *` parameter (can be NULL).

if the parameter is missing, it is a user error and not a bug in libre.
this is not possible to fix since it is using `va_args`.

**Pull request merged**
