### PR TITLE
Add a list of error handlers for audio errors

### PR DESCRIPTION
**Pull request by larsimmisch**
This is useful when using `audio_set_source` with the `aufile` module and a filename: when the file has played to the end, the error handler is called with a 0 error code and the message `end of file`. This is sometimes needed by an application/module.

### CODE REVIEW

**Comment by alfredh** [comment]
this PR looks okay, but have you tried to use UA events:

https://github.com/baresip/baresip/blob/main/include/baresip.h#L800

**Comment by larsimmisch** [comment]
I observe the UA events, but the `end of file` will not be sent as a `UA_EVENT_AUDIO_ERROR`, because the error code is 0 in this case and `UA_EVENT_AUDIO_ERROR` is only sent for real errors.

**Comment by larsimmisch** [comment]
It would be an alternative to also send `UA_EVENT_AUDIO_ERROR` for error code 0, but that might break existing code. If you'd be ok with that breakage, your suggestion seems a better solution.

**Comment by paresy** [comment]
As far as i remember this was the case in older baresip versions and was "fixed" to only send this message when real errors happen

**Comment by larsimmisch** [comment]
Closing this in favor of #2755 (this is even simpler and more in line with the existing code)

**Pull request closed without merging**
