### PR TITLE
Disable verify server cert

### PR DESCRIPTION
**Pull request by cspiel1**
Allows to disable the SIP TLS server verification if configured in accounts. By default the server verification is enabled for SIP TLS.

TODO: testing

### CODE REVIEW

**Comment by cspiel1** [comment]
Per account disable of SIP TLS server verification is to complicated in libre. The benefit is too low compared to a config flag.

replaced by https://github.com/baresip/baresip/pull/1224

**Comment by juha-h** [comment]
I build baresip from master and then started it using existing configuration/account. I got to console:
```
config: no sip_cafile defined and sip_verify_server is enabled, sip tls connections maybe won't work
```
and
```
tls: verify_handler: err          = 19
tls: verify_handler: error_string = self signed certificate in certificate chain
tls: verify_handler: depth        = 3
tls: connect: error (r=-1, ssl_err=1)
reg: sip:foo@bar.com (prio 0): Register: Protocol error
```
Was it intentional to break backwards compatibility?

**Comment by cspiel1** [comment]
yes, previously SIP TLS was not secure. The remote certificate was not verified. You could use a real certificate and specify a CA-file or disable sip_verify_server in the accounts file.

**Comment by juha-h** [comment]
Christian Spielberger writes:

> yes, previously SIP TLS was not secure. The remote certificate was not
> verified. You could use a real certificate and specify a CA-file or
> disable sip_verify_server in the accounts file.

Yes, I know I can do that, but still, I don't consider breaking existing
baresip configurations a good idea. You could have created new default
configs with

sip_verify_server	yes

and keep 'no' as the default.

-- Juha

**Comment by cspiel1** [comment]
Yes, ok. I will make a PR.

**Comment by cspiel1** [comment]
@juha-h Please vote for https://github.com/baresip/baresip/pull/1236 if it is ok for you?

**Pull request closed without merging**
