### PR TITLE
Update video in menu when UA_EVENT_CALL_REMOTE_SDP is recieved

### PR DESCRIPTION
**Pull request by juha-h**

### CODE REVIEW

**Comment by cspiel1** [comment]
In call.c `UA_EVENT_CALL_REMOTE_SDP` is sent in function `update_media()`.
There is already:
```c
	if (stream_is_ready(video_strm(call->video))) {
		err |= video_update(call->video, call->peer_uri);
	}
```

Is'nt it called twice now?

**Comment by juha-h** [comment]
Christian Spielberger writes:

> In call.c `UA_EVENT_CALL_REMOTE_SDP` is sent in function `update_media()`.
> There is already:
> ```c
> 	if (stream_is_ready(video_strm(call->video))) {
> 		err |= video_update(call->video, call->peer_uri);
> 	}
> ```
> 
> Is'nt it called twice now?

If it is only the one done in menu has the desired effect.  In the above,
the call is made when stream is ready.  Is the stream ready when video
has been disabled?

If not, perhaps the same test could be added to menu that I proposed
earlier:

if (vrdir == SDP_INACTIVE)
    video_update(call->video, call->peer_uri);

**Comment by cspiel1** [comment]
The stream is not ready in case of `SDP_INACTIVE`. What exactly was missing before this PR?

**Comment by juha-h** [comment]
X11 window was not closed when video was made inactive.

**Comment by cspiel1** [comment]
I understand. I will have a look. I guess the solution should be in `call.c`.

**Comment by juha-h** [comment]
Thanks, I didn't dare to touch the core.

**Comment by cspiel1** [comment]
Your solution works only if `menu` is loaded.

**Comment by juha-h** [comment]
Yes, but in most cases when X11 display is used, menu is also used. But any improvement is of course welcome.

**Pull request merged**
