### PR TITLE
Merge stable release v2.8.0

### PR DESCRIPTION
**Pull request by cspiel1**

### CODE REVIEW

**Comment by cspiel1** [comment]
@sreimers may I merge the stable?

**Comment by sreimers** [comment]
> @sreimers may I merge the stable?

Merge and push should be fine too.

**Comment by alfredh** [comment]
great work!

**Comment by cspiel1** [comment]
ok, thanks!
But see the newest baresip PR! There is a little mistake with the baresip version number in the header file.

**Comment by cspiel1** [comment]
@sreimers please could you complete the stable merge? I will look in the afternoon what exactly are your steps.

**Comment by cspiel1** [comment]
Ah, nothing more? So thanks for guiding me!

**Comment by sreimers** [comment]
Yes if there is no conflict, merge is enough. Only if we release from stable branch we have to select the correct branch on the release page (instead main).

**Pull request merged**
